# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_addElement.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 294)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.element_name = QtWidgets.QLineEdit(self.centralwidget)
        self.element_name.setObjectName("element_name")
        self.horizontalLayout_2.addWidget(self.element_name)
        self.element_name_error = QtWidgets.QLabel(self.centralwidget)
        self.element_name_error.setObjectName("element_name_error")
        self.horizontalLayout_2.addWidget(self.element_name_error)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lattice = QtWidgets.QLineEdit(self.centralwidget)
        self.lattice.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lattice.setObjectName("lattice")
        self.horizontalLayout_3.addWidget(self.lattice)
        self.angstroms_label = QtWidgets.QLabel(self.centralwidget)
        self.angstroms_label.setObjectName("angstroms_label")
        self.horizontalLayout_3.addWidget(self.angstroms_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.crystal_structure = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crystal_structure.sizePolicy().hasHeightForWidth())
        self.crystal_structure.setSizePolicy(sizePolicy)
        self.crystal_structure.setMinimumSize(QtCore.QSize(0, 0))
        self.crystal_structure.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.crystal_structure.setObjectName("crystal_structure")
        self.crystal_structure.addItem("")
        self.crystal_structure.addItem("")
        self.horizontalLayout_4.addWidget(self.crystal_structure)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setEnabled(False)
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Data = QtWidgets.QAction(MainWindow)
        self.action1_Data.setObjectName("action1_Data")
        self.action2_Normalization = QtWidgets.QAction(MainWindow)
        self.action2_Normalization.setEnabled(True)
        self.action2_Normalization.setObjectName("action2_Normalization")
        self.action3_Binning = QtWidgets.QAction(MainWindow)
        self.action3_Binning.setObjectName("action3_Binning")
        self.action4_Fitting = QtWidgets.QAction(MainWindow)
        self.action4_Fitting.setObjectName("action4_Fitting")
        self.action5_Results = QtWidgets.QAction(MainWindow)
        self.action5_Results.setObjectName("action5_Results")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action1_Raw_Data = QtWidgets.QAction(MainWindow)
        self.action1_Raw_Data.setObjectName("action1_Raw_Data")
        self.action2_Normalization_2 = QtWidgets.QAction(MainWindow)
        self.action2_Normalization_2.setObjectName("action2_Normalization_2")
        self.action3_Normalized_Data = QtWidgets.QAction(MainWindow)
        self.action3_Normalized_Data.setObjectName("action3_Normalized_Data")

        self.retranslateUi(MainWindow)
        self.cancel.clicked.connect(MainWindow.cancel_clicked)
        self.add.clicked.connect(MainWindow.add_clicked)
        self.element_name.textChanged['QString'].connect(MainWindow.element_name_changed)
        self.lattice.textChanged['QString'].connect(MainWindow.lattice_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Element Name:"))
        self.element_name_error.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#d91d35;\">Pick Unique Name!</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Lattice:"))
        self.angstroms_label.setText(_translate("MainWindow", "A"))
        self.label_3.setText(_translate("MainWindow", "Crystal Structure:"))
        self.crystal_structure.setItemText(0, _translate("MainWindow", "FCC"))
        self.crystal_structure.setItemText(1, _translate("MainWindow", "BCC"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.action1_Data.setText(_translate("MainWindow", "1. Data"))
        self.action2_Normalization.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Binning.setText(_translate("MainWindow", "4. Binning"))
        self.action4_Fitting.setText(_translate("MainWindow", "5. Fitting"))
        self.action5_Results.setText(_translate("MainWindow", "6. Strain Mapping"))
        self.actionAbout.setText(_translate("MainWindow", "About ..."))
        self.action1_Raw_Data.setText(_translate("MainWindow", "1. Raw Data"))
        self.action2_Normalization_2.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Normalized_Data.setText(_translate("MainWindow", "3. Normalized Data"))

