# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_fittingStoryTable.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.story_table = QtWidgets.QTableWidget(self.centralwidget)
        self.story_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.story_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.story_table.setObjectName("story_table")
        self.story_table.setColumnCount(8)
        self.story_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.story_table.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_2.addWidget(self.story_table)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_button = QtWidgets.QPushButton(self.centralwidget)
        self.up_button.setMinimumSize(QtCore.QSize(20, 30))
        self.up_button.setMaximumSize(QtCore.QSize(20, 30))
        self.up_button.setText("")
        self.up_button.setObjectName("up_button")
        self.verticalLayout.addWidget(self.up_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.down_button = QtWidgets.QPushButton(self.centralwidget)
        self.down_button.setMinimumSize(QtCore.QSize(20, 30))
        self.down_button.setMaximumSize(QtCore.QSize(20, 30))
        self.down_button.setText("")
        self.down_button.setObjectName("down_button")
        self.verticalLayout.addWidget(self.down_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_row_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_row_button.setEnabled(True)
        self.add_row_button.setMinimumSize(QtCore.QSize(40, 30))
        self.add_row_button.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.add_row_button.setFont(font)
        self.add_row_button.setObjectName("add_row_button")
        self.horizontalLayout.addWidget(self.add_row_button)
        self.remove_row_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_row_button.setEnabled(False)
        self.remove_row_button.setMinimumSize(QtCore.QSize(40, 30))
        self.remove_row_button.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.remove_row_button.setFont(font)
        self.remove_row_button.setObjectName("remove_row_button")
        self.horizontalLayout.addWidget(self.remove_row_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.start_fits_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_fits_button.sizePolicy().hasHeightForWidth())
        self.start_fits_button.setSizePolicy(sizePolicy)
        self.start_fits_button.setMinimumSize(QtCore.QSize(100, 20))
        self.start_fits_button.setMaximumSize(QtCore.QSize(300, 40))
        self.start_fits_button.setObjectName("start_fits_button")
        self.horizontalLayout.addWidget(self.start_fits_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 22))
        self.menubar.setObjectName("menubar")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuTable.addAction(self.actionReset)
        self.menubar.addAction(self.menuTable.menuAction())

        self.retranslateUi(MainWindow)
        self.add_row_button.clicked.connect(MainWindow.add_row_button_clicked)
        self.remove_row_button.clicked.connect(MainWindow.remove_row_button_clicked)
        self.start_fits_button.clicked.connect(MainWindow.start_fitting_button_clicked)
        self.up_button.clicked.connect(MainWindow.move_row_up_clicked)
        self.down_button.clicked.connect(MainWindow.move_row_down_clicked)
        self.story_table.cellClicked['int','int'].connect(MainWindow.cell_clicked)
        self.actionReset.triggered.connect(MainWindow.reset_table)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fitting Story"))
        self.label.setText(_translate("MainWindow", "Check Variables to Fit"))
        item = self.story_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "D_spacing"))
        item = self.story_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sigma"))
        item = self.story_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alpha"))
        item = self.story_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "A1"))
        item = self.story_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "A2"))
        item = self.story_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "A5"))
        item = self.story_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "A6"))
        item = self.story_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "STATUS"))
        self.add_row_button.setText(_translate("MainWindow", "+"))
        self.remove_row_button.setText(_translate("MainWindow", "-"))
        self.start_fits_button.setText(_translate("MainWindow", "Start Fits"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))

