# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_fittingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 785)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.rightFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy)
        self.rightFrame.setMinimumSize(QtCore.QSize(300, 400))
        self.rightFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.rightFrame)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 274, 320))
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.material_groupBox = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.material_groupBox.sizePolicy().hasHeightForWidth())
        self.material_groupBox.setSizePolicy(sizePolicy)
        self.material_groupBox.setTitle("")
        self.material_groupBox.setObjectName("material_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.material_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.material_groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.hkl_list_ui = QtWidgets.QComboBox(self.material_groupBox)
        self.hkl_list_ui.setMinimumSize(QtCore.QSize(100, 0))
        self.hkl_list_ui.setMaximumSize(QtCore.QSize(100, 16777215))
        self.hkl_list_ui.setObjectName("hkl_list_ui")
        self.horizontalLayout.addWidget(self.hkl_list_ui)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.material_groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.bragg_edge_calculated = QtWidgets.QLabel(self.material_groupBox)
        self.bragg_edge_calculated.setMinimumSize(QtCore.QSize(50, 0))
        self.bragg_edge_calculated.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bragg_edge_calculated.setObjectName("bragg_edge_calculated")
        self.horizontalLayout_2.addWidget(self.bragg_edge_calculated)
        self.bragg_edge_units = QtWidgets.QLabel(self.material_groupBox)
        self.bragg_edge_units.setObjectName("bragg_edge_units")
        self.horizontalLayout_2.addWidget(self.bragg_edge_units)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.material_groupBox)
        self.lambda_range_selected = QtWidgets.QGroupBox(self.page)
        self.lambda_range_selected.setObjectName("lambda_range_selected")
        self.gridLayout = QtWidgets.QGridLayout(self.lambda_range_selected)
        self.gridLayout.setObjectName("gridLayout")
        self.lambda_min_label = QtWidgets.QLabel(self.lambda_range_selected)
        self.lambda_min_label.setObjectName("lambda_min_label")
        self.gridLayout.addWidget(self.lambda_min_label, 0, 0, 1, 1)
        self.lambda_min_lineEdit = QtWidgets.QLineEdit(self.lambda_range_selected)
        self.lambda_min_lineEdit.setObjectName("lambda_min_lineEdit")
        self.gridLayout.addWidget(self.lambda_min_lineEdit, 0, 1, 1, 1)
        self.lambda_min_units = QtWidgets.QLabel(self.lambda_range_selected)
        self.lambda_min_units.setObjectName("lambda_min_units")
        self.gridLayout.addWidget(self.lambda_min_units, 0, 2, 1, 1)
        self.lambda_max_label = QtWidgets.QLabel(self.lambda_range_selected)
        self.lambda_max_label.setObjectName("lambda_max_label")
        self.gridLayout.addWidget(self.lambda_max_label, 1, 0, 1, 1)
        self.lambda_max_lineEdit = QtWidgets.QLineEdit(self.lambda_range_selected)
        self.lambda_max_lineEdit.setObjectName("lambda_max_lineEdit")
        self.gridLayout.addWidget(self.lambda_max_lineEdit, 1, 1, 1, 1)
        self.lambda_max_units = QtWidgets.QLabel(self.lambda_range_selected)
        self.lambda_max_units.setObjectName("lambda_max_units")
        self.gridLayout.addWidget(self.lambda_max_units, 1, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.lambda_range_selected)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 274, 320))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.step1_step2_instructions_label = QtWidgets.QTextEdit(self.page_2)
        self.step1_step2_instructions_label.setEnabled(False)
        self.step1_step2_instructions_label.setMinimumSize(QtCore.QSize(0, 50))
        self.step1_step2_instructions_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.step1_step2_instructions_label.setReadOnly(True)
        self.step1_step2_instructions_label.setObjectName("step1_step2_instructions_label")
        self.verticalLayout_6.addWidget(self.step1_step2_instructions_label)
        self.instructions_step1_button = QtWidgets.QPushButton(self.page_2)
        self.instructions_step1_button.setEnabled(False)
        self.instructions_step1_button.setObjectName("instructions_step1_button")
        self.verticalLayout_6.addWidget(self.instructions_step1_button)
        self.step4_groupBox = QtWidgets.QGroupBox(self.page_2)
        self.step4_groupBox.setEnabled(False)
        self.step4_groupBox.setObjectName("step4_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.step4_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fit_table_active_cell_button = QtWidgets.QPushButton(self.step4_groupBox)
        self.fit_table_active_cell_button.setEnabled(False)
        self.fit_table_active_cell_button.setObjectName("fit_table_active_cell_button")
        self.verticalLayout_2.addWidget(self.fit_table_active_cell_button)
        self.label_4 = QtWidgets.QLabel(self.step4_groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.create_fitting_story_button = QtWidgets.QPushButton(self.step4_groupBox)
        self.create_fitting_story_button.setObjectName("create_fitting_story_button")
        self.verticalLayout_2.addWidget(self.create_fitting_story_button)
        self.verticalLayout_6.addWidget(self.step4_groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.bottomFrame = QtWidgets.QFrame(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomFrame.sizePolicy().hasHeightForWidth())
        self.bottomFrame.setSizePolicy(sizePolicy)
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bottomFrame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.bottomFrame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.show_all_bins = QtWidgets.QRadioButton(self.groupBox_2)
        self.show_all_bins.setChecked(True)
        self.show_all_bins.setObjectName("show_all_bins")
        self.horizontalLayout_5.addWidget(self.show_all_bins)
        self.show_only_active_bins = QtWidgets.QRadioButton(self.groupBox_2)
        self.show_only_active_bins.setObjectName("show_only_active_bins")
        self.horizontalLayout_5.addWidget(self.show_only_active_bins)
        self.show_only_lock_bins = QtWidgets.QRadioButton(self.groupBox_2)
        self.show_only_lock_bins.setObjectName("show_only_lock_bins")
        self.horizontalLayout_5.addWidget(self.show_only_lock_bins)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.advanced_table_checkBox = QtWidgets.QCheckBox(self.bottomFrame)
        self.advanced_table_checkBox.setEnabled(True)
        self.advanced_table_checkBox.setChecked(False)
        self.advanced_table_checkBox.setObjectName("advanced_table_checkBox")
        self.horizontalLayout_4.addWidget(self.advanced_table_checkBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.header_table = QtWidgets.QTableWidget(self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_table.sizePolicy().hasHeightForWidth())
        self.header_table.setSizePolicy(sizePolicy)
        self.header_table.setMinimumSize(QtCore.QSize(1180, 0))
        self.header_table.setMaximumSize(QtCore.QSize(1180, 22))
        self.header_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.header_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_table.setAutoScroll(True)
        self.header_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.header_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.header_table.setCornerButtonEnabled(True)
        self.header_table.setObjectName("header_table")
        self.header_table.setColumnCount(13)
        self.header_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.header_table.setHorizontalHeaderItem(12, item)
        self.header_table.horizontalHeader().setVisible(True)
        self.header_table.horizontalHeader().setHighlightSections(True)
        self.header_table.horizontalHeader().setStretchLastSection(False)
        self.header_table.verticalHeader().setVisible(False)
        self.header_table.verticalHeader().setHighlightSections(False)
        self.header_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.header_table)
        self.value_table = QtWidgets.QTableWidget(self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_table.sizePolicy().hasHeightForWidth())
        self.value_table.setSizePolicy(sizePolicy)
        self.value_table.setMinimumSize(QtCore.QSize(1180, 0))
        self.value_table.setMaximumSize(QtCore.QSize(1180, 16777215))
        self.value_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.value_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.value_table.setLineWidth(1)
        self.value_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.value_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.value_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.value_table.setObjectName("value_table")
        self.value_table.setColumnCount(21)
        self.value_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(20, item)
        self.value_table.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.value_table)
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.hkl_list_ui.currentIndexChanged['QString'].connect(MainWindow.hkl_list_changed)
        self.value_table.customContextMenuRequested['QPoint'].connect(MainWindow.value_table_right_click)
        self.value_table.cellClicked['int','int'].connect(MainWindow.selection_in_value_table_of_rows_cell_clicked)
        self.value_table.itemSelectionChanged.connect(MainWindow.selection_in_value_table_changed)
        self.advanced_table_checkBox.clicked['bool'].connect(MainWindow.advanced_table_clicked)
        self.show_all_bins.clicked.connect(MainWindow.update_table)
        self.show_only_active_bins.clicked.connect(MainWindow.update_table)
        self.show_only_lock_bins.clicked.connect(MainWindow.update_table)
        self.instructions_step1_button.clicked.connect(MainWindow.initialize_all_parameters_button_clicked)
        self.lambda_min_lineEdit.returnPressed.connect(MainWindow.min_or_max_lambda_manually_changed)
        self.lambda_max_lineEdit.returnPressed.connect(MainWindow.min_or_max_lambda_manually_changed)
        self.fit_table_active_cell_button.clicked.connect(MainWindow.fit_table_active_cell_checked)
        self.create_fitting_story_button.clicked.connect(MainWindow.create_fitting_story_checked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "h,k,l"))
        self.label_2.setText(_translate("MainWindow", "calculated"))
        self.bragg_edge_calculated.setText(_translate("MainWindow", "N/A"))
        self.bragg_edge_units.setText(_translate("MainWindow", "A"))
        self.lambda_range_selected.setTitle(_translate("MainWindow", "Range Selected"))
        self.lambda_min_label.setText(_translate("MainWindow", "Lambda min"))
        self.lambda_min_units.setText(_translate("MainWindow", "A"))
        self.lambda_max_label.setText(_translate("MainWindow", "Lambda max"))
        self.lambda_max_units.setText(_translate("MainWindow", "A"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Bragg Edge Infos"))
        self.step1_step2_instructions_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">step1 - makes all bins <span style=\" font-weight:600;\">active</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">step2 -<span style=\" font-weight:600;\"> </span>selects Bragg Edge peak</p></body></html>"))
        self.instructions_step1_button.setToolTip(_translate("MainWindow", "Program determines inital guess value of parameters and fits data using 1 global bin"))
        self.instructions_step1_button.setText(_translate("MainWindow", "step3 - Initialize All Parameters"))
        self.step4_groupBox.setTitle(_translate("MainWindow", "step4"))
        self.fit_table_active_cell_button.setText(_translate("MainWindow", "Fit Table Active Cell"))
        self.label_4.setText(_translate("MainWindow", "or"))
        self.create_fitting_story_button.setText(_translate("MainWindow", "Create Fitting Story ..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Fitting Instructions"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bins To Display"))
        self.show_all_bins.setText(_translate("MainWindow", "Show All"))
        self.show_only_active_bins.setText(_translate("MainWindow", "Show Only Active"))
        self.show_only_lock_bins.setText(_translate("MainWindow", "Show Only Lock"))
        self.advanced_table_checkBox.setText(_translate("MainWindow", "Advanced Fitting"))
        item = self.header_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row"))
        item = self.header_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Col"))
        item = self.header_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lock"))
        item = self.header_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Active"))
        item = self.header_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fitting Confidence"))
        item = self.header_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "D-spacing"))
        item = self.header_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sigma"))
        item = self.header_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Alpha"))
        item = self.header_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "A1"))
        item = self.header_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "A2"))
        item = self.header_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "A5"))
        item = self.header_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "A6"))
        item = self.header_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Intensity"))
        item = self.value_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Err."))
        item = self.value_table.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Val."))
        item = self.value_table.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Err."))

