# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_fittingSetVariables.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 772)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.d_spacing_button = QtWidgets.QRadioButton(self.groupBox)
        self.d_spacing_button.setChecked(True)
        self.d_spacing_button.setObjectName("d_spacing_button")
        self.horizontalLayout.addWidget(self.d_spacing_button)
        self.sigma_button = QtWidgets.QRadioButton(self.groupBox)
        self.sigma_button.setObjectName("sigma_button")
        self.horizontalLayout.addWidget(self.sigma_button)
        self.alpha_button = QtWidgets.QRadioButton(self.groupBox)
        self.alpha_button.setObjectName("alpha_button")
        self.horizontalLayout.addWidget(self.alpha_button)
        self.a1_button = QtWidgets.QRadioButton(self.groupBox)
        self.a1_button.setObjectName("a1_button")
        self.horizontalLayout.addWidget(self.a1_button)
        self.a2_button = QtWidgets.QRadioButton(self.groupBox)
        self.a2_button.setObjectName("a2_button")
        self.horizontalLayout.addWidget(self.a2_button)
        self.a5_button = QtWidgets.QRadioButton(self.groupBox)
        self.a5_button.setObjectName("a5_button")
        self.horizontalLayout.addWidget(self.a5_button)
        self.a6_button = QtWidgets.QRadioButton(self.groupBox)
        self.a6_button.setObjectName("a6_button")
        self.horizontalLayout.addWidget(self.a6_button)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.variable_table = QtWidgets.QTableWidget(self.centralwidget)
        self.variable_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.variable_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.variable_table.setObjectName("variable_table")
        self.variable_table.setColumnCount(0)
        self.variable_table.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.variable_table)
        self.colorscale_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorscale_table.sizePolicy().hasHeightForWidth())
        self.colorscale_table.setSizePolicy(sizePolicy)
        self.colorscale_table.setMinimumSize(QtCore.QSize(75, 0))
        self.colorscale_table.setMaximumSize(QtCore.QSize(75, 16777215))
        self.colorscale_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.colorscale_table.setObjectName("colorscale_table")
        self.colorscale_table.setColumnCount(1)
        self.colorscale_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.colorscale_table.setHorizontalHeaderItem(0, item)
        self.colorscale_table.horizontalHeader().setVisible(False)
        self.colorscale_table.horizontalHeader().setStretchLastSection(True)
        self.colorscale_table.verticalHeader().setVisible(False)
        self.colorscale_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.colorscale_table)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.active_label = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 35, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 28, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 146, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 35, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 28, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 146, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.active_label.setPalette(palette)
        self.active_label.setObjectName("active_label")
        self.horizontalLayout_5.addWidget(self.active_label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.locked_label = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(193, 22, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 22, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.locked_label.setPalette(palette)
        self.locked_label.setObjectName("locked_label")
        self.horizontalLayout_5.addWidget(self.locked_label)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fixed_label = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.fixed_label.setPalette(palette)
        self.fixed_label.setObjectName("fixed_label")
        self.horizontalLayout_5.addWidget(self.fixed_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.advanced_selection_cell_size_slider = QtWidgets.QSlider(self.centralwidget)
        self.advanced_selection_cell_size_slider.setMinimum(10)
        self.advanced_selection_cell_size_slider.setMaximum(80)
        self.advanced_selection_cell_size_slider.setProperty("value", 20)
        self.advanced_selection_cell_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.advanced_selection_cell_size_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.advanced_selection_cell_size_slider.setObjectName("advanced_selection_cell_size_slider")
        self.horizontalLayout_5.addWidget(self.advanced_selection_cell_size_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.new_value_text_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.new_value_text_edit.setMinimumSize(QtCore.QSize(100, 0))
        self.new_value_text_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.new_value_text_edit.setObjectName("new_value_text_edit")
        self.horizontalLayout_2.addWidget(self.new_value_text_edit)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setMinimumSize(QtCore.QSize(250, 0))
        self.apply_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_2.addWidget(self.apply_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.advanced_selection_cell_size_slider.sliderMoved['int'].connect(MainWindow.selection_cell_size_changed)
        self.d_spacing_button.clicked.connect(MainWindow.update_table)
        self.sigma_button.clicked.connect(MainWindow.update_table)
        self.alpha_button.clicked.connect(MainWindow.update_table)
        self.a1_button.clicked.connect(MainWindow.update_table)
        self.a2_button.clicked.connect(MainWindow.update_table)
        self.a5_button.clicked.connect(MainWindow.update_table)
        self.a6_button.clicked.connect(MainWindow.update_table)
        self.variable_table.customContextMenuRequested['QPoint'].connect(MainWindow.variable_table_right_click)
        self.apply_button.clicked.connect(MainWindow.apply_new_value_to_selection)
        self.new_value_text_edit.returnPressed.connect(MainWindow.apply_new_value_to_selection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Variables"))
        self.d_spacing_button.setText(_translate("MainWindow", "D-spacing"))
        self.sigma_button.setText(_translate("MainWindow", "Sigma"))
        self.alpha_button.setText(_translate("MainWindow", "Alpha"))
        self.a1_button.setText(_translate("MainWindow", "A1"))
        self.a2_button.setText(_translate("MainWindow", "A2"))
        self.a5_button.setText(_translate("MainWindow", "A5"))
        self.a6_button.setText(_translate("MainWindow", "A6"))
        item = self.colorscale_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.active_label.setText(_translate("MainWindow", "Active Bin"))
        self.locked_label.setText(_translate("MainWindow", "Bin Locked"))
        self.fixed_label.setText(_translate("MainWindow", "Fixed"))
        self.label_2.setText(_translate("MainWindow", "Cells Size"))
        self.label.setText(_translate("MainWindow", "New Value"))
        self.apply_button.setText(_translate("MainWindow", "Apply New Value to Selection"))

