# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1534, 1001)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1508, 950))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1300, 950))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.load_data_splitter = QtGui.QSplitter(self.tab)
        self.load_data_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.load_data_splitter.setObjectName(_fromUtf8("load_data_splitter"))
        self.sample_ob_splitter = QtGui.QSplitter(self.load_data_splitter)
        self.sample_ob_splitter.setMinimumSize(QtCore.QSize(300, 0))
        self.sample_ob_splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sample_ob_splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sample_ob_splitter.setOrientation(QtCore.Qt.Vertical)
        self.sample_ob_splitter.setObjectName(_fromUtf8("sample_ob_splitter"))
        self.widget = QtGui.QWidget(self.sample_ob_splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.toolBox = QtGui.QToolBox(self.widget)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.sample_toolbox = QtGui.QWidget()
        self.sample_toolbox.setGeometry(QtCore.QRect(0, 0, 883, 369))
        self.sample_toolbox.setObjectName(_fromUtf8("sample_toolbox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.sample_toolbox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.import_sample_button = QtGui.QPushButton(self.sample_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_sample_button.sizePolicy().hasHeightForWidth())
        self.import_sample_button.setSizePolicy(sizePolicy)
        self.import_sample_button.setObjectName(_fromUtf8("import_sample_button"))
        self.horizontalLayout_4.addWidget(self.import_sample_button)
        self.sample_folder = QtGui.QLabel(self.sample_toolbox)
        self.sample_folder.setText(_fromUtf8(""))
        self.sample_folder.setObjectName(_fromUtf8("sample_folder"))
        self.horizontalLayout_4.addWidget(self.sample_folder)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.list_sample = QtGui.QListWidget(self.sample_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sample.sizePolicy().hasHeightForWidth())
        self.list_sample.setSizePolicy(sizePolicy)
        self.list_sample.setMinimumSize(QtCore.QSize(50, 0))
        self.list_sample.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_sample.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.list_sample.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.list_sample.setObjectName(_fromUtf8("list_sample"))
        self.verticalLayout_5.addWidget(self.list_sample)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.toolBox.addItem(self.sample_toolbox, _fromUtf8(""))
        self.open_beam_toolbox = QtGui.QWidget()
        self.open_beam_toolbox.setGeometry(QtCore.QRect(0, 0, 883, 369))
        self.open_beam_toolbox.setObjectName(_fromUtf8("open_beam_toolbox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.open_beam_toolbox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.import_open_beam_button = QtGui.QPushButton(self.open_beam_toolbox)
        self.import_open_beam_button.setObjectName(_fromUtf8("import_open_beam_button"))
        self.horizontalLayout_5.addWidget(self.import_open_beam_button)
        self.open_beam_folder = QtGui.QLabel(self.open_beam_toolbox)
        self.open_beam_folder.setText(_fromUtf8(""))
        self.open_beam_folder.setObjectName(_fromUtf8("open_beam_folder"))
        self.horizontalLayout_5.addWidget(self.open_beam_folder)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.list_open_beam = QtGui.QListWidget(self.open_beam_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_open_beam.sizePolicy().hasHeightForWidth())
        self.list_open_beam.setSizePolicy(sizePolicy)
        self.list_open_beam.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list_open_beam.setObjectName(_fromUtf8("list_open_beam"))
        self.verticalLayout_7.addWidget(self.list_open_beam)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.open_beam_toolbox, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.toolBox)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_9.addWidget(self.line)
        self.time_spectra_2 = QtGui.QGroupBox(self.widget)
        self.time_spectra_2.setMinimumSize(QtCore.QSize(0, 110))
        self.time_spectra_2.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_spectra_2.setFont(font)
        self.time_spectra_2.setObjectName(_fromUtf8("time_spectra_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.time_spectra_2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.import_time_spectra_button = QtGui.QPushButton(self.time_spectra_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.import_time_spectra_button.setSizePolicy(sizePolicy)
        self.import_time_spectra_button.setObjectName(_fromUtf8("import_time_spectra_button"))
        self.horizontalLayout_3.addWidget(self.import_time_spectra_button)
        self.time_spectra_folder = QtGui.QLabel(self.time_spectra_2)
        self.time_spectra_folder.setAutoFillBackground(False)
        self.time_spectra_folder.setText(_fromUtf8(""))
        self.time_spectra_folder.setObjectName(_fromUtf8("time_spectra_folder"))
        self.horizontalLayout_3.addWidget(self.time_spectra_folder)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.preview_time_spectra_button = QtGui.QPushButton(self.time_spectra_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.preview_time_spectra_button.setSizePolicy(sizePolicy)
        self.preview_time_spectra_button.setObjectName(_fromUtf8("preview_time_spectra_button"))
        self.horizontalLayout_3.addWidget(self.preview_time_spectra_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.time_spectra = QtGui.QLabel(self.time_spectra_2)
        self.time_spectra.setText(_fromUtf8(""))
        self.time_spectra.setObjectName(_fromUtf8("time_spectra"))
        self.horizontalLayout_6.addWidget(self.time_spectra)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.time_spectra_2)
        self.tabWidget_2 = QtGui.QTabWidget(self.sample_ob_splitter)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.data_general_infos = QtGui.QTextEdit(self.tab_4)
        self.data_general_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_general_infos.setObjectName(_fromUtf8("data_general_infos"))
        self.verticalLayout_2.addWidget(self.data_general_infos)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.data_selected_infos = QtGui.QTextEdit(self.tab_4)
        self.data_selected_infos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_selected_infos.sizePolicy().hasHeightForWidth())
        self.data_selected_infos.setSizePolicy(sizePolicy)
        self.data_selected_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_selected_infos.setBaseSize(QtCore.QSize(0, 20))
        self.data_selected_infos.setObjectName(_fromUtf8("data_selected_infos"))
        self.verticalLayout.addWidget(self.data_selected_infos)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.beam_rate = QtGui.QComboBox(self.groupBox_2)
        self.beam_rate.setMinimumSize(QtCore.QSize(70, 0))
        self.beam_rate.setMaximumSize(QtCore.QSize(70, 16777215))
        self.beam_rate.setObjectName(_fromUtf8("beam_rate"))
        self.beam_rate.addItem(_fromUtf8(""))
        self.beam_rate.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.beam_rate, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.distance_source_detector = QtGui.QLineEdit(self.groupBox_2)
        self.distance_source_detector.setObjectName(_fromUtf8("distance_source_detector"))
        self.gridLayout_2.addWidget(self.distance_source_detector, 0, 1, 1, 1)
        self.delta_lambda_value = QtGui.QLabel(self.groupBox_2)
        self.delta_lambda_value.setObjectName(_fromUtf8("delta_lambda_value"))
        self.gridLayout_2.addWidget(self.delta_lambda_value, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.detector_offset = QtGui.QLineEdit(self.groupBox_2)
        self.detector_offset.setObjectName(_fromUtf8("detector_offset"))
        self.gridLayout_2.addWidget(self.detector_offset, 2, 1, 1, 1)
        self.delta_lambda_label = QtGui.QLabel(self.groupBox_2)
        self.delta_lambda_label.setMinimumSize(QtCore.QSize(20, 0))
        self.delta_lambda_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.delta_lambda_label.setObjectName(_fromUtf8("delta_lambda_label"))
        self.gridLayout_2.addWidget(self.delta_lambda_label, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.distance_source_detector_label = QtGui.QLabel(self.groupBox_2)
        self.distance_source_detector_label.setMinimumSize(QtCore.QSize(80, 0))
        self.distance_source_detector_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.distance_source_detector_label.setObjectName(_fromUtf8("distance_source_detector_label"))
        self.gridLayout_2.addWidget(self.distance_source_detector_label, 0, 0, 1, 1)
        self.micro_s = QtGui.QLabel(self.groupBox_2)
        self.micro_s.setObjectName(_fromUtf8("micro_s"))
        self.gridLayout_2.addWidget(self.micro_s, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 1, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.list_of_elements = QtGui.QComboBox(self.groupBox_3)
        self.list_of_elements.setEditable(True)
        self.list_of_elements.setObjectName(_fromUtf8("list_of_elements"))
        self.horizontalLayout_16.addWidget(self.list_of_elements)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setMinimumSize(QtCore.QSize(110, 0))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lattice_parameter = QtGui.QLineEdit(self.groupBox_3)
        self.lattice_parameter.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lattice_parameter.setObjectName(_fromUtf8("lattice_parameter"))
        self.horizontalLayout_17.addWidget(self.lattice_parameter)
        self.angstroms_label = QtGui.QLabel(self.groupBox_3)
        self.angstroms_label.setObjectName(_fromUtf8("angstroms_label"))
        self.horizontalLayout_17.addWidget(self.angstroms_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setMinimumSize(QtCore.QSize(110, 0))
        self.label_14.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.crystal_structure = QtGui.QComboBox(self.groupBox_3)
        self.crystal_structure.setMinimumSize(QtCore.QSize(100, 0))
        self.crystal_structure.setMaximumSize(QtCore.QSize(100, 16777215))
        self.crystal_structure.setObjectName(_fromUtf8("crystal_structure"))
        self.crystal_structure.addItem(_fromUtf8(""))
        self.crystal_structure.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.crystal_structure)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.image_preview = QtGui.QStackedWidget(self.load_data_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_preview.sizePolicy().hasHeightForWidth())
        self.image_preview.setSizePolicy(sizePolicy)
        self.image_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.image_preview.setSizeIncrement(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.image_preview.setFont(font)
        self.image_preview.setObjectName(_fromUtf8("image_preview"))
        self.sample_preview = QtGui.QWidget()
        self.sample_preview.setObjectName(_fromUtf8("sample_preview"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sample_preview)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.preview_widget = QtGui.QWidget(self.sample_preview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_widget.sizePolicy().hasHeightForWidth())
        self.preview_widget.setSizePolicy(sizePolicy)
        self.preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.preview_widget.setSizeIncrement(QtCore.QSize(0, 50))
        self.preview_widget.setBaseSize(QtCore.QSize(0, 300))
        self.preview_widget.setObjectName(_fromUtf8("preview_widget"))
        self.verticalLayout_3.addWidget(self.preview_widget)
        self.image_preview.addWidget(self.sample_preview)
        self.ob_preview = QtGui.QWidget()
        self.ob_preview.setObjectName(_fromUtf8("ob_preview"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.ob_preview)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.ob_preview_widget = QtGui.QWidget(self.ob_preview)
        self.ob_preview_widget.setObjectName(_fromUtf8("ob_preview_widget"))
        self.verticalLayout_10.addWidget(self.ob_preview_widget)
        self.image_preview.addWidget(self.ob_preview)
        self.horizontalLayout.addWidget(self.load_data_splitter)
        self.tabWidget_2.raise_()
        self.image_preview.raise_()
        self.ob_preview_widget.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.normalized_splitter = QtGui.QSplitter(self.tab_3)
        self.normalized_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.normalized_splitter.setObjectName(_fromUtf8("normalized_splitter"))
        self.widget1 = QtGui.QWidget(self.normalized_splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.import_normalized_data = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_normalized_data.sizePolicy().hasHeightForWidth())
        self.import_normalized_data.setSizePolicy(sizePolicy)
        self.import_normalized_data.setObjectName(_fromUtf8("import_normalized_data"))
        self.horizontalLayout_2.addWidget(self.import_normalized_data)
        self.normalized_folder = QtGui.QLabel(self.widget1)
        self.normalized_folder.setText(_fromUtf8(""))
        self.normalized_folder.setObjectName(_fromUtf8("normalized_folder"))
        self.horizontalLayout_2.addWidget(self.normalized_folder)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.list_normalized = QtGui.QListWidget(self.widget1)
        self.list_normalized.setObjectName(_fromUtf8("list_normalized"))
        self.verticalLayout_12.addWidget(self.list_normalized)
        self.time_spectra_3 = QtGui.QGroupBox(self.widget1)
        self.time_spectra_3.setMinimumSize(QtCore.QSize(0, 110))
        self.time_spectra_3.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_spectra_3.setFont(font)
        self.time_spectra_3.setObjectName(_fromUtf8("time_spectra_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.time_spectra_3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.import_time_spectra_button_2 = QtGui.QPushButton(self.time_spectra_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_time_spectra_button_2.sizePolicy().hasHeightForWidth())
        self.import_time_spectra_button_2.setSizePolicy(sizePolicy)
        self.import_time_spectra_button_2.setObjectName(_fromUtf8("import_time_spectra_button_2"))
        self.horizontalLayout_7.addWidget(self.import_time_spectra_button_2)
        self.time_spectra_folder_2 = QtGui.QLabel(self.time_spectra_3)
        self.time_spectra_folder_2.setAutoFillBackground(False)
        self.time_spectra_folder_2.setText(_fromUtf8(""))
        self.time_spectra_folder_2.setObjectName(_fromUtf8("time_spectra_folder_2"))
        self.horizontalLayout_7.addWidget(self.time_spectra_folder_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.preview_time_spectra_button_2 = QtGui.QPushButton(self.time_spectra_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_time_spectra_button_2.sizePolicy().hasHeightForWidth())
        self.preview_time_spectra_button_2.setSizePolicy(sizePolicy)
        self.preview_time_spectra_button_2.setObjectName(_fromUtf8("preview_time_spectra_button_2"))
        self.horizontalLayout_7.addWidget(self.preview_time_spectra_button_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.time_spectra_4 = QtGui.QLabel(self.time_spectra_3)
        self.time_spectra_4.setText(_fromUtf8(""))
        self.time_spectra_4.setObjectName(_fromUtf8("time_spectra_4"))
        self.horizontalLayout_12.addWidget(self.time_spectra_4)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addWidget(self.time_spectra_3)
        self.tabWidget_3 = QtGui.QTabWidget(self.widget1)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab_6)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.normalized_general_infos = QtGui.QTextEdit(self.tab_6)
        self.normalized_general_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.normalized_general_infos.setObjectName(_fromUtf8("normalized_general_infos"))
        self.verticalLayout_4.addWidget(self.normalized_general_infos)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_8 = QtGui.QLabel(self.tab_6)
        self.label_8.setMinimumSize(QtCore.QSize(0, 15))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.normalized_selected_infos = QtGui.QTextEdit(self.tab_6)
        self.normalized_selected_infos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_selected_infos.sizePolicy().hasHeightForWidth())
        self.normalized_selected_infos.setSizePolicy(sizePolicy)
        self.normalized_selected_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.normalized_selected_infos.setBaseSize(QtCore.QSize(0, 20))
        self.normalized_selected_infos.setObjectName(_fromUtf8("normalized_selected_infos"))
        self.verticalLayout_11.addWidget(self.normalized_selected_infos)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.beam_rate_2 = QtGui.QComboBox(self.groupBox_4)
        self.beam_rate_2.setMinimumSize(QtCore.QSize(70, 0))
        self.beam_rate_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.beam_rate_2.setObjectName(_fromUtf8("beam_rate_2"))
        self.beam_rate_2.addItem(_fromUtf8(""))
        self.beam_rate_2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.beam_rate_2, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.distance_source_detector_2 = QtGui.QLineEdit(self.groupBox_4)
        self.distance_source_detector_2.setObjectName(_fromUtf8("distance_source_detector_2"))
        self.gridLayout_4.addWidget(self.distance_source_detector_2, 0, 1, 1, 1)
        self.delta_lambda_value_2 = QtGui.QLabel(self.groupBox_4)
        self.delta_lambda_value_2.setObjectName(_fromUtf8("delta_lambda_value_2"))
        self.gridLayout_4.addWidget(self.delta_lambda_value_2, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.detector_offset_2 = QtGui.QLineEdit(self.groupBox_4)
        self.detector_offset_2.setObjectName(_fromUtf8("detector_offset_2"))
        self.gridLayout_4.addWidget(self.detector_offset_2, 2, 1, 1, 1)
        self.delta_lambda_label_2 = QtGui.QLabel(self.groupBox_4)
        self.delta_lambda_label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.delta_lambda_label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.delta_lambda_label_2.setObjectName(_fromUtf8("delta_lambda_label_2"))
        self.gridLayout_4.addWidget(self.delta_lambda_label_2, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setMinimumSize(QtCore.QSize(75, 0))
        self.label_15.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.distance_source_detector_label_2 = QtGui.QLabel(self.groupBox_4)
        self.distance_source_detector_label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.distance_source_detector_label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.distance_source_detector_label_2.setObjectName(_fromUtf8("distance_source_detector_label_2"))
        self.gridLayout_4.addWidget(self.distance_source_detector_label_2, 0, 0, 1, 1)
        self.micro_s_2 = QtGui.QLabel(self.groupBox_4)
        self.micro_s_2.setObjectName(_fromUtf8("micro_s_2"))
        self.gridLayout_4.addWidget(self.micro_s_2, 2, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 4, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setMinimumSize(QtCore.QSize(110, 0))
        self.label_18.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_19.addWidget(self.label_18)
        self.list_of_elements_2 = QtGui.QComboBox(self.groupBox_5)
        self.list_of_elements_2.setObjectName(_fromUtf8("list_of_elements_2"))
        self.horizontalLayout_19.addWidget(self.list_of_elements_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setMinimumSize(QtCore.QSize(110, 0))
        self.label_16.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_20.addWidget(self.label_16)
        self.lattice_parameter_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lattice_parameter_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lattice_parameter_2.setObjectName(_fromUtf8("lattice_parameter_2"))
        self.horizontalLayout_20.addWidget(self.lattice_parameter_2)
        self.angstroms_label_2 = QtGui.QLabel(self.groupBox_5)
        self.angstroms_label_2.setObjectName(_fromUtf8("angstroms_label_2"))
        self.horizontalLayout_20.addWidget(self.angstroms_label_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setMinimumSize(QtCore.QSize(110, 0))
        self.label_17.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_21.addWidget(self.label_17)
        self.crystal_structure_2 = QtGui.QComboBox(self.groupBox_5)
        self.crystal_structure_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.crystal_structure_2.setObjectName(_fromUtf8("crystal_structure_2"))
        self.crystal_structure_2.addItem(_fromUtf8(""))
        self.crystal_structure_2.addItem(_fromUtf8(""))
        self.horizontalLayout_21.addWidget(self.crystal_structure_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_21)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.horizontalLayout_14.addWidget(self.groupBox_5)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout_12.addWidget(self.tabWidget_3)
        self.normalized_preview_widget = QtGui.QWidget(self.normalized_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_preview_widget.sizePolicy().hasHeightForWidth())
        self.normalized_preview_widget.setSizePolicy(sizePolicy)
        self.normalized_preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.normalized_preview_widget.setSizeIncrement(QtCore.QSize(0, 50))
        self.normalized_preview_widget.setBaseSize(QtCore.QSize(0, 300))
        self.normalized_preview_widget.setObjectName(_fromUtf8("normalized_preview_widget"))
        self.horizontalLayout_15.addWidget(self.normalized_splitter)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1534, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSteps = QtGui.QMenu(self.menubar)
        self.menuSteps.setObjectName(_fromUtf8("menuSteps"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Data = QtGui.QAction(MainWindow)
        self.action1_Data.setObjectName(_fromUtf8("action1_Data"))
        self.action2_Normalization = QtGui.QAction(MainWindow)
        self.action2_Normalization.setEnabled(True)
        self.action2_Normalization.setObjectName(_fromUtf8("action2_Normalization"))
        self.action3_Binning = QtGui.QAction(MainWindow)
        self.action3_Binning.setObjectName(_fromUtf8("action3_Binning"))
        self.action4_Fitting = QtGui.QAction(MainWindow)
        self.action4_Fitting.setObjectName(_fromUtf8("action4_Fitting"))
        self.action5_Results = QtGui.QAction(MainWindow)
        self.action5_Results.setObjectName(_fromUtf8("action5_Results"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action1_Raw_Data = QtGui.QAction(MainWindow)
        self.action1_Raw_Data.setObjectName(_fromUtf8("action1_Raw_Data"))
        self.action2_Normalization_2 = QtGui.QAction(MainWindow)
        self.action2_Normalization_2.setObjectName(_fromUtf8("action2_Normalization_2"))
        self.action3_Normalized_Data = QtGui.QAction(MainWindow)
        self.action3_Normalized_Data.setObjectName(_fromUtf8("action3_Normalized_Data"))
        self.menuSteps.addAction(self.action1_Raw_Data)
        self.menuSteps.addAction(self.action2_Normalization_2)
        self.menuSteps.addAction(self.action3_Normalized_Data)
        self.menuSteps.addAction(self.action3_Binning)
        self.menuSteps.addAction(self.action4_Fitting)
        self.menuSteps.addAction(self.action5_Results)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSteps.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.image_preview.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QObject.connect(self.import_sample_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sample_import_button_clicked)
        QtCore.QObject.connect(self.import_time_spectra_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.time_spectra_import_button_clicked)
        QtCore.QObject.connect(self.import_open_beam_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.open_beam_import_button_clicked)
        QtCore.QObject.connect(self.list_sample, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.sample_list_selection_changed)
        QtCore.QObject.connect(self.list_open_beam, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.open_beam_list_selection_changed)
        QtCore.QObject.connect(self.list_sample, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainWindow.sample_list_right_click)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.load_data_tab_changed)
        QtCore.QObject.connect(self.preview_time_spectra_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.time_spectra_preview_button_clicked)
        QtCore.QObject.connect(self.import_normalized_data, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.normalized_import_button_clicked)
        QtCore.QObject.connect(self.list_normalized, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.normalized_list_selection_changed)
        QtCore.QObject.connect(self.distance_source_detector, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.update_delta_lambda)
        QtCore.QObject.connect(self.beam_rate, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.update_delta_lambda)
        QtCore.QObject.connect(self.crystal_structure, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.crystal_structure_index_changed)
        QtCore.QObject.connect(self.crystal_structure_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.crystal_structure_2_index_changed)
        QtCore.QObject.connect(self.list_of_elements, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.list_of_element_index_changed)
        QtCore.QObject.connect(self.list_of_elements_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.list_of_element_2_index_changed)
        QtCore.QObject.connect(self.lattice_parameter_2, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.lattice_2_text_changed)
        QtCore.QObject.connect(self.lattice_parameter, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.lattice_text_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.import_sample_button.setText(_translate("MainWindow", "Import ...", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sample_toolbox), _translate("MainWindow", " Sample", None))
        self.import_open_beam_button.setText(_translate("MainWindow", "Import ...", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.open_beam_toolbox), _translate("MainWindow", " Open Beam", None))
        self.time_spectra_2.setTitle(_translate("MainWindow", "Time Spectra", None))
        self.import_time_spectra_button.setText(_translate("MainWindow", "Import ...", None))
        self.preview_time_spectra_button.setText(_translate("MainWindow", "Preview ...", None))
        self.label_2.setText(_translate("MainWindow", "All Files", None))
        self.label.setText(_translate("MainWindow", "Selected File", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Infos", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Instrument", None))
        self.beam_rate.setItemText(0, _translate("MainWindow", "60", None))
        self.beam_rate.setItemText(1, _translate("MainWindow", "30", None))
        self.label_4.setText(_translate("MainWindow", "Hz", None))
        self.distance_source_detector.setText(_translate("MainWindow", "15", None))
        self.delta_lambda_value.setText(_translate("MainWindow", "N/A", None))
        self.label_7.setText(_translate("MainWindow", "Detector offset", None))
        self.detector_offset.setText(_translate("MainWindow", "5000", None))
        self.delta_lambda_label.setText(_translate("MainWindow", "delta_lambda:", None))
        self.label_6.setText(_translate("MainWindow", "m", None))
        self.label_3.setText(_translate("MainWindow", "Beam Rate", None))
        self.distance_source_detector_label.setText(_translate("MainWindow", "d source-detector", None))
        self.micro_s.setText(_translate("MainWindow", "micros", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Material", None))
        self.label_12.setText(_translate("MainWindow", "Element", None))
        self.label_13.setText(_translate("MainWindow", "Lattice", None))
        self.angstroms_label.setText(_translate("MainWindow", "A", None))
        self.label_14.setText(_translate("MainWindow", "Crystal Structure", None))
        self.crystal_structure.setItemText(0, _translate("MainWindow", "FCC", None))
        self.crystal_structure.setItemText(1, _translate("MainWindow", "BCC", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1 - Load Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2 - Normalization", None))
        self.import_normalized_data.setText(_translate("MainWindow", "Import ...", None))
        self.time_spectra_3.setTitle(_translate("MainWindow", "Time Spectra", None))
        self.import_time_spectra_button_2.setText(_translate("MainWindow", "Import ...", None))
        self.preview_time_spectra_button_2.setText(_translate("MainWindow", "Preview ...", None))
        self.label_5.setText(_translate("MainWindow", "All Files", None))
        self.label_8.setText(_translate("MainWindow", "Selected File", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Infos", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Instrument", None))
        self.beam_rate_2.setItemText(0, _translate("MainWindow", "60", None))
        self.beam_rate_2.setItemText(1, _translate("MainWindow", "30", None))
        self.label_9.setText(_translate("MainWindow", "Hz", None))
        self.distance_source_detector_2.setText(_translate("MainWindow", "15", None))
        self.delta_lambda_value_2.setText(_translate("MainWindow", "N/A", None))
        self.label_10.setText(_translate("MainWindow", "Detector offset", None))
        self.detector_offset_2.setText(_translate("MainWindow", "5000", None))
        self.delta_lambda_label_2.setText(_translate("MainWindow", "delta_lambda:", None))
        self.label_11.setText(_translate("MainWindow", "m", None))
        self.label_15.setText(_translate("MainWindow", "Beam Rate", None))
        self.distance_source_detector_label_2.setText(_translate("MainWindow", "d source-detector", None))
        self.micro_s_2.setText(_translate("MainWindow", "micros", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Material", None))
        self.label_18.setText(_translate("MainWindow", "Element", None))
        self.label_16.setText(_translate("MainWindow", "Lattice", None))
        self.angstroms_label_2.setText(_translate("MainWindow", "A", None))
        self.label_17.setText(_translate("MainWindow", "Crystal Structure", None))
        self.crystal_structure_2.setItemText(0, _translate("MainWindow", "FCC", None))
        self.crystal_structure_2.setItemText(1, _translate("MainWindow", "BCC", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3 - Normalized Data", None))
        self.menuSteps.setTitle(_translate("MainWindow", "Steps", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.action1_Data.setText(_translate("MainWindow", "1. Data", None))
        self.action2_Normalization.setText(_translate("MainWindow", "2. Normalization", None))
        self.action3_Binning.setText(_translate("MainWindow", "4. Binning", None))
        self.action4_Fitting.setText(_translate("MainWindow", "5. Fitting", None))
        self.action5_Results.setText(_translate("MainWindow", "6. Strain Mapping", None))
        self.actionAbout.setText(_translate("MainWindow", "About ...", None))
        self.action1_Raw_Data.setText(_translate("MainWindow", "1. Raw Data", None))
        self.action2_Normalization_2.setText(_translate("MainWindow", "2. Normalization", None))
        self.action3_Normalized_Data.setText(_translate("MainWindow", "3. Normalized Data", None))

