# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1534, 1001)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1493, 950))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1300, 950))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_data_splitter = QtWidgets.QSplitter(self.tab)
        self.load_data_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.load_data_splitter.setObjectName("load_data_splitter")
        self.sample_ob_splitter = QtWidgets.QSplitter(self.load_data_splitter)
        self.sample_ob_splitter.setMinimumSize(QtCore.QSize(300, 0))
        self.sample_ob_splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sample_ob_splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sample_ob_splitter.setOrientation(QtCore.Qt.Vertical)
        self.sample_ob_splitter.setObjectName("sample_ob_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.sample_ob_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toolBox = QtWidgets.QToolBox(self.layoutWidget)
        self.toolBox.setObjectName("toolBox")
        self.sample_toolbox = QtWidgets.QWidget()
        self.sample_toolbox.setGeometry(QtCore.QRect(0, 0, 1368, 375))
        self.sample_toolbox.setObjectName("sample_toolbox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sample_toolbox)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.import_sample_button = QtWidgets.QPushButton(self.sample_toolbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_sample_button.sizePolicy().hasHeightForWidth())
        self.import_sample_button.setSizePolicy(sizePolicy)
        self.import_sample_button.setObjectName("import_sample_button")
        self.horizontalLayout_4.addWidget(self.import_sample_button)
        self.sample_folder = QtWidgets.QLabel(self.sample_toolbox)
        self.sample_folder.setText("")
        self.sample_folder.setObjectName("sample_folder")
        self.horizontalLayout_4.addWidget(self.sample_folder)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.list_sample = QtWidgets.QListWidget(self.sample_toolbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sample.sizePolicy().hasHeightForWidth())
        self.list_sample.setSizePolicy(sizePolicy)
        self.list_sample.setMinimumSize(QtCore.QSize(50, 0))
        self.list_sample.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_sample.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_sample.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_sample.setObjectName("list_sample")
        self.verticalLayout_5.addWidget(self.list_sample)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.toolBox.addItem(self.sample_toolbox, "")
        self.open_beam_toolbox = QtWidgets.QWidget()
        self.open_beam_toolbox.setGeometry(QtCore.QRect(0, 0, 1368, 375))
        self.open_beam_toolbox.setObjectName("open_beam_toolbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.open_beam_toolbox)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.import_open_beam_button = QtWidgets.QPushButton(self.open_beam_toolbox)
        self.import_open_beam_button.setObjectName("import_open_beam_button")
        self.horizontalLayout_5.addWidget(self.import_open_beam_button)
        self.open_beam_folder = QtWidgets.QLabel(self.open_beam_toolbox)
        self.open_beam_folder.setText("")
        self.open_beam_folder.setObjectName("open_beam_folder")
        self.horizontalLayout_5.addWidget(self.open_beam_folder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.list_open_beam = QtWidgets.QListWidget(self.open_beam_toolbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_open_beam.sizePolicy().hasHeightForWidth())
        self.list_open_beam.setSizePolicy(sizePolicy)
        self.list_open_beam.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_open_beam.setObjectName("list_open_beam")
        self.verticalLayout_7.addWidget(self.list_open_beam)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.open_beam_toolbox, "")
        self.verticalLayout_9.addWidget(self.toolBox)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.time_spectra_groupbox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.time_spectra_groupbox_2.setMinimumSize(QtCore.QSize(0, 110))
        self.time_spectra_groupbox_2.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_spectra_groupbox_2.setFont(font)
        self.time_spectra_groupbox_2.setObjectName("time_spectra_groupbox_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.time_spectra_groupbox_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.import_time_spectra_button = QtWidgets.QPushButton(self.time_spectra_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.import_time_spectra_button.setSizePolicy(sizePolicy)
        self.import_time_spectra_button.setObjectName("import_time_spectra_button")
        self.horizontalLayout_3.addWidget(self.import_time_spectra_button)
        self.time_spectra_folder = QtWidgets.QLabel(self.time_spectra_groupbox_2)
        self.time_spectra_folder.setAutoFillBackground(False)
        self.time_spectra_folder.setText("")
        self.time_spectra_folder.setObjectName("time_spectra_folder")
        self.horizontalLayout_3.addWidget(self.time_spectra_folder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.preview_time_spectra_button = QtWidgets.QPushButton(self.time_spectra_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.preview_time_spectra_button.setSizePolicy(sizePolicy)
        self.preview_time_spectra_button.setObjectName("preview_time_spectra_button")
        self.horizontalLayout_3.addWidget(self.preview_time_spectra_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.time_spectra = QtWidgets.QLabel(self.time_spectra_groupbox_2)
        self.time_spectra.setText("")
        self.time_spectra.setObjectName("time_spectra")
        self.horizontalLayout_6.addWidget(self.time_spectra)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.time_spectra_groupbox_2)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.sample_ob_splitter)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.data_general_infos = QtWidgets.QTextEdit(self.tab_4)
        self.data_general_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_general_infos.setObjectName("data_general_infos")
        self.verticalLayout_2.addWidget(self.data_general_infos)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.data_selected_infos = QtWidgets.QTextEdit(self.tab_4)
        self.data_selected_infos.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_selected_infos.sizePolicy().hasHeightForWidth())
        self.data_selected_infos.setSizePolicy(sizePolicy)
        self.data_selected_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_selected_infos.setBaseSize(QtCore.QSize(0, 20))
        self.data_selected_infos.setObjectName("data_selected_infos")
        self.verticalLayout.addWidget(self.data_selected_infos)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.delta_lambda_value = QtWidgets.QLabel(self.groupBox_2)
        self.delta_lambda_value.setObjectName("delta_lambda_value")
        self.gridLayout_2.addWidget(self.delta_lambda_value, 3, 1, 1, 1)
        self.distance_source_detector = QtWidgets.QLineEdit(self.groupBox_2)
        self.distance_source_detector.setObjectName("distance_source_detector")
        self.gridLayout_2.addWidget(self.distance_source_detector, 0, 1, 1, 1)
        self.detector_offset = QtWidgets.QLineEdit(self.groupBox_2)
        self.detector_offset.setObjectName("detector_offset")
        self.gridLayout_2.addWidget(self.detector_offset, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.distance_source_detector_label = QtWidgets.QLabel(self.groupBox_2)
        self.distance_source_detector_label.setMinimumSize(QtCore.QSize(80, 0))
        self.distance_source_detector_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.distance_source_detector_label.setObjectName("distance_source_detector_label")
        self.gridLayout_2.addWidget(self.distance_source_detector_label, 0, 0, 1, 1)
        self.micro_s = QtWidgets.QLabel(self.groupBox_2)
        self.micro_s.setObjectName("micro_s")
        self.gridLayout_2.addWidget(self.micro_s, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 1, 1, 1)
        self.delta_lambda_label = QtWidgets.QLabel(self.groupBox_2)
        self.delta_lambda_label.setMinimumSize(QtCore.QSize(20, 0))
        self.delta_lambda_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.delta_lambda_label.setObjectName("delta_lambda_label")
        self.gridLayout_2.addWidget(self.delta_lambda_label, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.beam_rate = QtWidgets.QComboBox(self.groupBox_2)
        self.beam_rate.setMinimumSize(QtCore.QSize(70, 0))
        self.beam_rate.setMaximumSize(QtCore.QSize(70, 16777215))
        self.beam_rate.setObjectName("beam_rate")
        self.beam_rate.addItem("")
        self.beam_rate.addItem("")
        self.gridLayout_2.addWidget(self.beam_rate, 1, 1, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.material_display_checkbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.material_display_checkbox.setChecked(True)
        self.material_display_checkbox.setObjectName("material_display_checkbox")
        self.horizontalLayout_22.addWidget(self.material_display_checkbox)
        self.display_warning = QtWidgets.QLabel(self.groupBox_3)
        self.display_warning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display_warning.setObjectName("display_warning")
        self.horizontalLayout_22.addWidget(self.display_warning)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.list_of_elements = QtWidgets.QComboBox(self.groupBox_3)
        self.list_of_elements.setEditable(True)
        self.list_of_elements.setObjectName("list_of_elements")
        self.horizontalLayout_16.addWidget(self.list_of_elements)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setMinimumSize(QtCore.QSize(30, 0))
        self.label_23.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_27.addWidget(self.label_23)
        self.add_element = QtWidgets.QPushButton(self.groupBox_3)
        self.add_element.setObjectName("add_element")
        self.horizontalLayout_27.addWidget(self.add_element)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setMinimumSize(QtCore.QSize(110, 0))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lattice_parameter = QtWidgets.QLineEdit(self.groupBox_3)
        self.lattice_parameter.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lattice_parameter.setObjectName("lattice_parameter")
        self.horizontalLayout_17.addWidget(self.lattice_parameter)
        self.angstroms_label = QtWidgets.QLabel(self.groupBox_3)
        self.angstroms_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.angstroms_label.setObjectName("angstroms_label")
        self.horizontalLayout_17.addWidget(self.angstroms_label)
        self.reset_lattice_button = QtWidgets.QPushButton(self.groupBox_3)
        self.reset_lattice_button.setMinimumSize(QtCore.QSize(20, 20))
        self.reset_lattice_button.setMaximumSize(QtCore.QSize(20, 20))
        self.reset_lattice_button.setText("")
        self.reset_lattice_button.setObjectName("reset_lattice_button")
        self.horizontalLayout_17.addWidget(self.reset_lattice_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setMinimumSize(QtCore.QSize(110, 0))
        self.label_14.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.crystal_structure = QtWidgets.QComboBox(self.groupBox_3)
        self.crystal_structure.setMinimumSize(QtCore.QSize(100, 0))
        self.crystal_structure.setMaximumSize(QtCore.QSize(100, 16777215))
        self.crystal_structure.setObjectName("crystal_structure")
        self.crystal_structure.addItem("")
        self.crystal_structure.addItem("")
        self.horizontalLayout_18.addWidget(self.crystal_structure)
        self.reset_crystal_structure_button = QtWidgets.QPushButton(self.groupBox_3)
        self.reset_crystal_structure_button.setMinimumSize(QtCore.QSize(20, 20))
        self.reset_crystal_structure_button.setMaximumSize(QtCore.QSize(20, 20))
        self.reset_crystal_structure_button.setText("")
        self.reset_crystal_structure_button.setObjectName("reset_crystal_structure_button")
        self.horizontalLayout_18.addWidget(self.reset_crystal_structure_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.image_preview = QtWidgets.QStackedWidget(self.load_data_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_preview.sizePolicy().hasHeightForWidth())
        self.image_preview.setSizePolicy(sizePolicy)
        self.image_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.image_preview.setSizeIncrement(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.image_preview.setFont(font)
        self.image_preview.setObjectName("image_preview")
        self.sample_preview = QtWidgets.QWidget()
        self.sample_preview.setObjectName("sample_preview")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sample_preview)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.preview_widget = QtWidgets.QWidget(self.sample_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_widget.sizePolicy().hasHeightForWidth())
        self.preview_widget.setSizePolicy(sizePolicy)
        self.preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.preview_widget.setSizeIncrement(QtCore.QSize(0, 50))
        self.preview_widget.setBaseSize(QtCore.QSize(0, 300))
        self.preview_widget.setObjectName("preview_widget")
        self.verticalLayout_3.addWidget(self.preview_widget)
        self.image_preview.addWidget(self.sample_preview)
        self.ob_preview = QtWidgets.QWidget()
        self.ob_preview.setObjectName("ob_preview")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ob_preview)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ob_preview_widget = QtWidgets.QWidget(self.ob_preview)
        self.ob_preview_widget.setObjectName("ob_preview_widget")
        self.verticalLayout_10.addWidget(self.ob_preview_widget)
        self.image_preview.addWidget(self.ob_preview)
        self.horizontalLayout.addWidget(self.load_data_splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.splitter = QtWidgets.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.normalization_left_widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalization_left_widget.sizePolicy().hasHeightForWidth())
        self.normalization_left_widget.setSizePolicy(sizePolicy)
        self.normalization_left_widget.setObjectName("normalization_left_widget")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_17.addWidget(self.label_19)
        self.normalization_tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.normalization_tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.normalization_tableWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.normalization_tableWidget.setAlternatingRowColors(True)
        self.normalization_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.normalization_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.normalization_tableWidget.setObjectName("normalization_tableWidget")
        self.normalization_tableWidget.setColumnCount(5)
        self.normalization_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.normalization_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.normalization_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.normalization_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.normalization_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.normalization_tableWidget.setHorizontalHeaderItem(4, item)
        self.normalization_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.normalization_tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_17.addWidget(self.normalization_tableWidget)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.normalization_add_roi_button = QtWidgets.QPushButton(self.widget_2)
        self.normalization_add_roi_button.setMinimumSize(QtCore.QSize(30, 30))
        self.normalization_add_roi_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.normalization_add_roi_button.setFont(font)
        self.normalization_add_roi_button.setObjectName("normalization_add_roi_button")
        self.horizontalLayout_25.addWidget(self.normalization_add_roi_button)
        self.normalization_remove_roi_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalization_remove_roi_button.sizePolicy().hasHeightForWidth())
        self.normalization_remove_roi_button.setSizePolicy(sizePolicy)
        self.normalization_remove_roi_button.setMinimumSize(QtCore.QSize(30, 30))
        self.normalization_remove_roi_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.normalization_remove_roi_button.setFont(font)
        self.normalization_remove_roi_button.setObjectName("normalization_remove_roi_button")
        self.horizontalLayout_25.addWidget(self.normalization_remove_roi_button)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem8)
        self.verticalLayout_17.addLayout(self.horizontalLayout_25)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem9)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_19.addWidget(self.label_20)
        self.verticalLayout_17.addWidget(self.groupBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem10)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.normalization_button = QtWidgets.QPushButton(self.widget_2)
        self.normalization_button.setEnabled(False)
        self.normalization_button.setObjectName("normalization_button")
        self.horizontalLayout_26.addWidget(self.normalization_button)
        self.verticalLayout_17.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.normalized_splitter = QtWidgets.QSplitter(self.tab_3)
        self.normalized_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.normalized_splitter.setObjectName("normalized_splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.normalized_splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.import_normalized_data = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_normalized_data.sizePolicy().hasHeightForWidth())
        self.import_normalized_data.setSizePolicy(sizePolicy)
        self.import_normalized_data.setObjectName("import_normalized_data")
        self.horizontalLayout_2.addWidget(self.import_normalized_data)
        self.normalized_folder = QtWidgets.QLabel(self.layoutWidget1)
        self.normalized_folder.setText("")
        self.normalized_folder.setObjectName("normalized_folder")
        self.horizontalLayout_2.addWidget(self.normalized_folder)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.list_normalized = QtWidgets.QListWidget(self.layoutWidget1)
        self.list_normalized.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_normalized.setObjectName("list_normalized")
        self.verticalLayout_12.addWidget(self.list_normalized)
        self.time_spectra_groupbox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.time_spectra_groupbox.setMinimumSize(QtCore.QSize(0, 110))
        self.time_spectra_groupbox.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_spectra_groupbox.setFont(font)
        self.time_spectra_groupbox.setObjectName("time_spectra_groupbox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.time_spectra_groupbox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.import_time_spectra_button_2 = QtWidgets.QPushButton(self.time_spectra_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_time_spectra_button_2.sizePolicy().hasHeightForWidth())
        self.import_time_spectra_button_2.setSizePolicy(sizePolicy)
        self.import_time_spectra_button_2.setObjectName("import_time_spectra_button_2")
        self.horizontalLayout_7.addWidget(self.import_time_spectra_button_2)
        self.time_spectra_folder_2 = QtWidgets.QLabel(self.time_spectra_groupbox)
        self.time_spectra_folder_2.setAutoFillBackground(False)
        self.time_spectra_folder_2.setText("")
        self.time_spectra_folder_2.setObjectName("time_spectra_folder_2")
        self.horizontalLayout_7.addWidget(self.time_spectra_folder_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.preview_time_spectra_button_2 = QtWidgets.QPushButton(self.time_spectra_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_time_spectra_button_2.sizePolicy().hasHeightForWidth())
        self.preview_time_spectra_button_2.setSizePolicy(sizePolicy)
        self.preview_time_spectra_button_2.setObjectName("preview_time_spectra_button_2")
        self.horizontalLayout_7.addWidget(self.preview_time_spectra_button_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.time_spectra_2 = QtWidgets.QLabel(self.time_spectra_groupbox)
        self.time_spectra_2.setText("")
        self.time_spectra_2.setObjectName("time_spectra_2")
        self.horizontalLayout_12.addWidget(self.time_spectra_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addWidget(self.time_spectra_groupbox)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.normalized_general_infos = QtWidgets.QTextEdit(self.tab_6)
        self.normalized_general_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.normalized_general_infos.setObjectName("normalized_general_infos")
        self.verticalLayout_4.addWidget(self.normalized_general_infos)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setMinimumSize(QtCore.QSize(0, 15))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.normalized_selected_infos = QtWidgets.QTextEdit(self.tab_6)
        self.normalized_selected_infos.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_selected_infos.sizePolicy().hasHeightForWidth())
        self.normalized_selected_infos.setSizePolicy(sizePolicy)
        self.normalized_selected_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.normalized_selected_infos.setBaseSize(QtCore.QSize(0, 20))
        self.normalized_selected_infos.setObjectName("normalized_selected_infos")
        self.verticalLayout_11.addWidget(self.normalized_selected_infos)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.beam_rate_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.beam_rate_2.setMinimumSize(QtCore.QSize(70, 0))
        self.beam_rate_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.beam_rate_2.setObjectName("beam_rate_2")
        self.beam_rate_2.addItem("")
        self.beam_rate_2.addItem("")
        self.gridLayout_4.addWidget(self.beam_rate_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.distance_source_detector_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.distance_source_detector_2.setObjectName("distance_source_detector_2")
        self.gridLayout_4.addWidget(self.distance_source_detector_2, 0, 1, 1, 1)
        self.delta_lambda_value_2 = QtWidgets.QLabel(self.groupBox_4)
        self.delta_lambda_value_2.setObjectName("delta_lambda_value_2")
        self.gridLayout_4.addWidget(self.delta_lambda_value_2, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.detector_offset_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.detector_offset_2.setObjectName("detector_offset_2")
        self.gridLayout_4.addWidget(self.detector_offset_2, 2, 1, 1, 1)
        self.delta_lambda_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.delta_lambda_label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.delta_lambda_label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.delta_lambda_label_2.setObjectName("delta_lambda_label_2")
        self.gridLayout_4.addWidget(self.delta_lambda_label_2, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setMinimumSize(QtCore.QSize(75, 0))
        self.label_15.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.distance_source_detector_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.distance_source_detector_label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.distance_source_detector_label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.distance_source_detector_label_2.setObjectName("distance_source_detector_label_2")
        self.gridLayout_4.addWidget(self.distance_source_detector_label_2, 0, 0, 1, 1)
        self.micro_s_2 = QtWidgets.QLabel(self.groupBox_4)
        self.micro_s_2.setObjectName("micro_s_2")
        self.gridLayout_4.addWidget(self.micro_s_2, 2, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 4, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.material_display_checkbox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.material_display_checkbox_2.setChecked(True)
        self.material_display_checkbox_2.setObjectName("material_display_checkbox_2")
        self.horizontalLayout_23.addWidget(self.material_display_checkbox_2)
        self.display_warning_2 = QtWidgets.QLabel(self.groupBox_5)
        self.display_warning_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display_warning_2.setObjectName("display_warning_2")
        self.horizontalLayout_23.addWidget(self.display_warning_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setMinimumSize(QtCore.QSize(110, 0))
        self.label_18.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.list_of_elements_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.list_of_elements_2.setObjectName("list_of_elements_2")
        self.horizontalLayout_19.addWidget(self.list_of_elements_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setMinimumSize(QtCore.QSize(30, 0))
        self.label_21.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_28.addWidget(self.label_21)
        self.add_element_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.add_element_3.setObjectName("add_element_3")
        self.horizontalLayout_28.addWidget(self.add_element_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setMinimumSize(QtCore.QSize(110, 0))
        self.label_16.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.lattice_parameter_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lattice_parameter_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lattice_parameter_2.setObjectName("lattice_parameter_2")
        self.horizontalLayout_20.addWidget(self.lattice_parameter_2)
        self.angstroms_label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.angstroms_label_2.setObjectName("angstroms_label_2")
        self.horizontalLayout_20.addWidget(self.angstroms_label_2)
        self.reset_lattice_button_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.reset_lattice_button_2.setMinimumSize(QtCore.QSize(20, 20))
        self.reset_lattice_button_2.setMaximumSize(QtCore.QSize(20, 20))
        self.reset_lattice_button_2.setText("")
        self.reset_lattice_button_2.setObjectName("reset_lattice_button_2")
        self.horizontalLayout_20.addWidget(self.reset_lattice_button_2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem16)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setMinimumSize(QtCore.QSize(110, 0))
        self.label_17.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_21.addWidget(self.label_17)
        self.crystal_structure_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.crystal_structure_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.crystal_structure_2.setObjectName("crystal_structure_2")
        self.crystal_structure_2.addItem("")
        self.crystal_structure_2.addItem("")
        self.horizontalLayout_21.addWidget(self.crystal_structure_2)
        self.reset_crystal_structure_button_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.reset_crystal_structure_button_2.setMinimumSize(QtCore.QSize(20, 20))
        self.reset_crystal_structure_button_2.setMaximumSize(QtCore.QSize(20, 20))
        self.reset_crystal_structure_button_2.setText("")
        self.reset_crystal_structure_button_2.setObjectName("reset_crystal_structure_button_2")
        self.horizontalLayout_21.addWidget(self.reset_crystal_structure_button_2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem17)
        self.verticalLayout_16.addLayout(self.horizontalLayout_21)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem18)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_16.addWidget(self.label_22)
        self.horizontalLayout_14.addWidget(self.groupBox_5)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.normalized_preview_widget = QtWidgets.QWidget(self.normalized_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_preview_widget.sizePolicy().hasHeightForWidth())
        self.normalized_preview_widget.setSizePolicy(sizePolicy)
        self.normalized_preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.normalized_preview_widget.setSizeIncrement(QtCore.QSize(0, 50))
        self.normalized_preview_widget.setBaseSize(QtCore.QSize(0, 300))
        self.normalized_preview_widget.setObjectName("normalized_preview_widget")
        self.verticalLayout_20.addWidget(self.normalized_splitter)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_9.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1534, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuSteps = QtWidgets.QMenu(self.menubar)
        self.menuSteps.setObjectName("menuSteps")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Data = QtWidgets.QAction(MainWindow)
        self.action1_Data.setObjectName("action1_Data")
        self.action2_Normalization = QtWidgets.QAction(MainWindow)
        self.action2_Normalization.setEnabled(True)
        self.action2_Normalization.setObjectName("action2_Normalization")
        self.action3_Binning = QtWidgets.QAction(MainWindow)
        self.action3_Binning.setObjectName("action3_Binning")
        self.action4_Fitting = QtWidgets.QAction(MainWindow)
        self.action4_Fitting.setObjectName("action4_Fitting")
        self.action5_Results = QtWidgets.QAction(MainWindow)
        self.action5_Results.setObjectName("action5_Results")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action1_load_data = QtWidgets.QAction(MainWindow)
        self.action1_load_data.setObjectName("action1_load_data")
        self.action2_Normalization_2 = QtWidgets.QAction(MainWindow)
        self.action2_Normalization_2.setObjectName("action2_Normalization_2")
        self.action3_Normalized_Data = QtWidgets.QAction(MainWindow)
        self.action3_Normalized_Data.setObjectName("action3_Normalized_Data")
        self.actionTest_me = QtWidgets.QAction(MainWindow)
        self.actionTest_me.setObjectName("actionTest_me")
        self.actionRotate_Images = QtWidgets.QAction(MainWindow)
        self.actionRotate_Images.setEnabled(False)
        self.actionRotate_Images.setObjectName("actionRotate_Images")
        self.menuSteps.addAction(self.action1_load_data)
        self.menuSteps.addAction(self.action2_Normalization_2)
        self.menuSteps.addAction(self.action3_Normalized_Data)
        self.menuSteps.addAction(self.action3_Binning)
        self.menuSteps.addAction(self.action4_Fitting)
        self.menuSteps.addAction(self.action5_Results)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionTest_me)
        self.menuTools.addAction(self.actionRotate_Images)
        self.menubar.addAction(self.menuSteps.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.image_preview.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.import_sample_button.clicked.connect(MainWindow.sample_import_button_clicked)
        self.import_time_spectra_button.clicked.connect(MainWindow.time_spectra_import_button_clicked)
        self.import_open_beam_button.clicked.connect(MainWindow.open_beam_import_button_clicked)
        self.list_sample.itemSelectionChanged.connect(MainWindow.sample_list_selection_changed)
        self.list_open_beam.itemSelectionChanged.connect(MainWindow.open_beam_list_selection_changed)
        self.list_sample.customContextMenuRequested['QPoint'].connect(MainWindow.sample_list_right_click)
        self.toolBox.currentChanged['int'].connect(MainWindow.load_data_tab_changed)
        self.preview_time_spectra_button.clicked.connect(MainWindow.time_spectra_preview_button_clicked)
        self.import_normalized_data.clicked.connect(MainWindow.normalized_import_button_clicked)
        self.list_normalized.itemSelectionChanged.connect(MainWindow.normalized_list_selection_changed)
        self.crystal_structure.currentIndexChanged['int'].connect(MainWindow.crystal_structure_index_changed)
        self.crystal_structure_2.currentIndexChanged['int'].connect(MainWindow.crystal_structure_2_index_changed)
        self.lattice_parameter_2.returnPressed.connect(MainWindow.lattice_2_text_changed)
        self.lattice_parameter.returnPressed.connect(MainWindow.lattice_text_changed)
        self.material_display_checkbox.clicked['bool'].connect(MainWindow.material_display_clicked)
        self.material_display_checkbox_2.clicked['bool'].connect(MainWindow.material_display_2_clicked)
        self.import_time_spectra_button_2.clicked.connect(MainWindow.normalized_time_spectra_import_button_clicked)
        self.preview_time_spectra_button_2.clicked.connect(MainWindow.normalized_time_spectra_preview_button_clicked)
        self.normalization_remove_roi_button.clicked.connect(MainWindow.normalization_remove_roi_button_clicked)
        self.normalization_add_roi_button.clicked.connect(MainWindow.normalization_add_roi_button_clicked)
        self.normalization_button.clicked.connect(MainWindow.normalization_button_clicked)
        self.tabWidget.currentChanged['int'].connect(MainWindow.tab_widget_changed)
        self.normalization_tableWidget.cellChanged['int','int'].connect(MainWindow.normalization_tableWidget_cell_changed)
        self.beam_rate.currentIndexChanged['int'].connect(MainWindow.beam_rate_changed)
        self.distance_source_detector.returnPressed.connect(MainWindow.distance_source_detector_changed)
        self.detector_offset.returnPressed.connect(MainWindow.detector_offset_changed)
        self.distance_source_detector_2.returnPressed.connect(MainWindow.distance_source_detector_2_changed)
        self.detector_offset_2.returnPressed.connect(MainWindow.detector_offset_2_changed)
        self.beam_rate_2.currentIndexChanged['int'].connect(MainWindow.beam_rate_2_changed)
        self.add_element.clicked.connect(MainWindow.add_element_clicked)
        self.add_element_3.clicked.connect(MainWindow.add_element_clicked)
        self.reset_lattice_button.clicked.connect(MainWindow.reset_lattice_button_clicked)
        self.reset_crystal_structure_button.clicked.connect(MainWindow.reset_crystal_structure_button_clicked)
        self.reset_lattice_button_2.clicked.connect(MainWindow.reset_lattice_button_2_clicked)
        self.reset_crystal_structure_button_2.clicked.connect(MainWindow.reset_crystal_structure_button_2_clicked)
        self.actionTest_me.triggered.connect(MainWindow.test_me_clicked)
        self.action1_load_data.triggered.connect(MainWindow.menu_view_load_data_clicked)
        self.action2_Normalization_2.triggered.connect(MainWindow.menu_view_normalization_clicked)
        self.action3_Normalized_Data.triggered.connect(MainWindow.menu_view_normalized_clicked)
        self.action3_Binning.triggered.connect(MainWindow.menu_view_binning_clicked)
        self.action4_Fitting.triggered.connect(MainWindow.menu_view_fitting_clicked)
        self.action5_Results.triggered.connect(MainWindow.menu_view_strain_mapping_clicked)
        self.actionRotate_Images.triggered.connect(MainWindow.rotate_normalized_images_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.import_sample_button.setText(_translate("MainWindow", "Import ..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sample_toolbox), _translate("MainWindow", " Sample"))
        self.import_open_beam_button.setText(_translate("MainWindow", "Import ..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.open_beam_toolbox), _translate("MainWindow", " Open Beam"))
        self.time_spectra_groupbox_2.setTitle(_translate("MainWindow", "Time Spectra"))
        self.import_time_spectra_button.setText(_translate("MainWindow", "Import ..."))
        self.preview_time_spectra_button.setText(_translate("MainWindow", "Preview ..."))
        self.label_2.setText(_translate("MainWindow", "All Files"))
        self.label.setText(_translate("MainWindow", "Selected File"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Infos"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Instrument"))
        self.label_4.setText(_translate("MainWindow", "Hz"))
        self.label_7.setText(_translate("MainWindow", "Detector offset"))
        self.delta_lambda_value.setText(_translate("MainWindow", "N/A"))
        self.distance_source_detector.setText(_translate("MainWindow", "15"))
        self.detector_offset.setText(_translate("MainWindow", "5000"))
        self.label_3.setText(_translate("MainWindow", "Beam Rate"))
        self.distance_source_detector_label.setText(_translate("MainWindow", "d source-detector"))
        self.micro_s.setText(_translate("MainWindow", "micros"))
        self.delta_lambda_label.setText(_translate("MainWindow", "delta_lambda:"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.beam_rate.setItemText(0, _translate("MainWindow", "60"))
        self.beam_rate.setItemText(1, _translate("MainWindow", "30"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Material"))
        self.material_display_checkbox.setText(_translate("MainWindow", "Display ?"))
        self.display_warning.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#c1162d;\">Time Spectra Missing !</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Select Element"))
        self.label_23.setText(_translate("MainWindow", "or"))
        self.add_element.setText(_translate("MainWindow", "Add New Element ..."))
        self.label_13.setText(_translate("MainWindow", "Lattice"))
        self.angstroms_label.setText(_translate("MainWindow", "A"))
        self.label_14.setText(_translate("MainWindow", "Crystal Structure"))
        self.crystal_structure.setItemText(0, _translate("MainWindow", "FCC"))
        self.crystal_structure.setItemText(1, _translate("MainWindow", "BCC"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1 - Load Data"))
        self.label_19.setText(_translate("MainWindow", "ROIs Manager"))
        item = self.normalization_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Use ?"))
        item = self.normalization_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Xo"))
        item = self.normalization_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yo"))
        item = self.normalization_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Width"))
        item = self.normalization_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Height"))
        self.normalization_add_roi_button.setText(_translate("MainWindow", "+"))
        self.normalization_remove_roi_button.setText(_translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "Instructions"))
        self.label_20.setText(_translate("MainWindow", "Select ROI(s) away from sample. "))
        self.normalization_button.setText(_translate("MainWindow", "Normalize ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2 - Normalization"))
        self.import_normalized_data.setText(_translate("MainWindow", "Import ..."))
        self.time_spectra_groupbox.setTitle(_translate("MainWindow", "Time Spectra"))
        self.import_time_spectra_button_2.setText(_translate("MainWindow", "Import ..."))
        self.preview_time_spectra_button_2.setText(_translate("MainWindow", "Preview ..."))
        self.label_5.setText(_translate("MainWindow", "All Files"))
        self.label_8.setText(_translate("MainWindow", "Selected File"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Infos"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Instrument"))
        self.beam_rate_2.setItemText(0, _translate("MainWindow", "60"))
        self.beam_rate_2.setItemText(1, _translate("MainWindow", "30"))
        self.label_9.setText(_translate("MainWindow", "Hz"))
        self.distance_source_detector_2.setText(_translate("MainWindow", "15"))
        self.delta_lambda_value_2.setText(_translate("MainWindow", "N/A"))
        self.label_10.setText(_translate("MainWindow", "Detector offset"))
        self.detector_offset_2.setText(_translate("MainWindow", "5000"))
        self.delta_lambda_label_2.setText(_translate("MainWindow", "delta_lambda:"))
        self.label_11.setText(_translate("MainWindow", "m"))
        self.label_15.setText(_translate("MainWindow", "Beam Rate"))
        self.distance_source_detector_label_2.setText(_translate("MainWindow", "d source-detector"))
        self.micro_s_2.setText(_translate("MainWindow", "micros"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Material"))
        self.material_display_checkbox_2.setText(_translate("MainWindow", "Display?"))
        self.display_warning_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#c1162d;\">Time Spectra Missing!</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Select Element"))
        self.label_21.setText(_translate("MainWindow", "or"))
        self.add_element_3.setText(_translate("MainWindow", "Add New Element ..."))
        self.label_16.setText(_translate("MainWindow", "Lattice"))
        self.angstroms_label_2.setText(_translate("MainWindow", "A"))
        self.label_17.setText(_translate("MainWindow", "Crystal Structure"))
        self.crystal_structure_2.setItemText(0, _translate("MainWindow", "FCC"))
        self.crystal_structure_2.setItemText(1, _translate("MainWindow", "BCC"))
        self.label_22.setText(_translate("MainWindow", "NB: those widgets are also used to define material in the Fitting (step 5) window."))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3 - Normalized Data"))
        self.menuSteps.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.action1_Data.setText(_translate("MainWindow", "1. Data"))
        self.action2_Normalization.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Binning.setText(_translate("MainWindow", "4. Binning"))
        self.action4_Fitting.setText(_translate("MainWindow", "5. Fitting"))
        self.action5_Results.setText(_translate("MainWindow", "6. Strain Mapping"))
        self.actionAbout.setText(_translate("MainWindow", "About ..."))
        self.action1_load_data.setText(_translate("MainWindow", "1. Load Data"))
        self.action2_Normalization_2.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Normalized_Data.setText(_translate("MainWindow", "3. Normalized Data"))
        self.actionTest_me.setText(_translate("MainWindow", "test_me"))
        self.actionRotate_Images.setText(_translate("MainWindow", "Rotate Normalized Images ..."))

