# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1534, 1001)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1508, 950))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1300, 950))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(self.layoutWidget)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.sample_toolbox = QtGui.QWidget()
        self.sample_toolbox.setGeometry(QtCore.QRect(0, 0, 602, 362))
        self.sample_toolbox.setObjectName(_fromUtf8("sample_toolbox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.sample_toolbox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.import_sample_button = QtGui.QPushButton(self.sample_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_sample_button.sizePolicy().hasHeightForWidth())
        self.import_sample_button.setSizePolicy(sizePolicy)
        self.import_sample_button.setObjectName(_fromUtf8("import_sample_button"))
        self.horizontalLayout_4.addWidget(self.import_sample_button)
        self.sample_folder = QtGui.QLabel(self.sample_toolbox)
        self.sample_folder.setText(_fromUtf8(""))
        self.sample_folder.setObjectName(_fromUtf8("sample_folder"))
        self.horizontalLayout_4.addWidget(self.sample_folder)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.list_sample = QtGui.QListWidget(self.sample_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sample.sizePolicy().hasHeightForWidth())
        self.list_sample.setSizePolicy(sizePolicy)
        self.list_sample.setMinimumSize(QtCore.QSize(50, 0))
        self.list_sample.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_sample.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.list_sample.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.list_sample.setObjectName(_fromUtf8("list_sample"))
        self.verticalLayout_5.addWidget(self.list_sample)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.toolBox.addItem(self.sample_toolbox, _fromUtf8(""))
        self.open_beam_toolbox = QtGui.QWidget()
        self.open_beam_toolbox.setGeometry(QtCore.QRect(0, 0, 602, 362))
        self.open_beam_toolbox.setObjectName(_fromUtf8("open_beam_toolbox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.open_beam_toolbox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.import_open_beam_button = QtGui.QPushButton(self.open_beam_toolbox)
        self.import_open_beam_button.setObjectName(_fromUtf8("import_open_beam_button"))
        self.horizontalLayout_5.addWidget(self.import_open_beam_button)
        self.open_beam_folder = QtGui.QLabel(self.open_beam_toolbox)
        self.open_beam_folder.setText(_fromUtf8(""))
        self.open_beam_folder.setObjectName(_fromUtf8("open_beam_folder"))
        self.horizontalLayout_5.addWidget(self.open_beam_folder)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.list_open_beam = QtGui.QListWidget(self.open_beam_toolbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_open_beam.sizePolicy().hasHeightForWidth())
        self.list_open_beam.setSizePolicy(sizePolicy)
        self.list_open_beam.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list_open_beam.setObjectName(_fromUtf8("list_open_beam"))
        self.verticalLayout_7.addWidget(self.list_open_beam)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.open_beam_toolbox, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.import_time_spectra_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.import_time_spectra_button.setSizePolicy(sizePolicy)
        self.import_time_spectra_button.setObjectName(_fromUtf8("import_time_spectra_button"))
        self.horizontalLayout_3.addWidget(self.import_time_spectra_button)
        self.time_spectra_folder = QtGui.QLabel(self.groupBox)
        self.time_spectra_folder.setText(_fromUtf8(""))
        self.time_spectra_folder.setObjectName(_fromUtf8("time_spectra_folder"))
        self.horizontalLayout_3.addWidget(self.time_spectra_folder)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.time_spectra = QtGui.QLabel(self.groupBox)
        self.time_spectra.setText(_fromUtf8(""))
        self.time_spectra.setObjectName(_fromUtf8("time_spectra"))
        self.horizontalLayout_6.addWidget(self.time_spectra)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.preview_time_spectra_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_time_spectra_button.sizePolicy().hasHeightForWidth())
        self.preview_time_spectra_button.setSizePolicy(sizePolicy)
        self.preview_time_spectra_button.setObjectName(_fromUtf8("preview_time_spectra_button"))
        self.horizontalLayout_6.addWidget(self.preview_time_spectra_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.data_infos_box = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_infos_box.sizePolicy().hasHeightForWidth())
        self.data_infos_box.setSizePolicy(sizePolicy)
        self.data_infos_box.setMinimumSize(QtCore.QSize(100, 20))
        self.data_infos_box.setMaximumSize(QtCore.QSize(16777215, 300))
        self.data_infos_box.setBaseSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_infos_box.setFont(font)
        self.data_infos_box.setObjectName(_fromUtf8("data_infos_box"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.data_infos_box)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label = QtGui.QLabel(self.data_infos_box)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_9.addWidget(self.label)
        self.data_selected_infos = QtGui.QTextEdit(self.data_infos_box)
        self.data_selected_infos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_selected_infos.sizePolicy().hasHeightForWidth())
        self.data_selected_infos.setSizePolicy(sizePolicy)
        self.data_selected_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_selected_infos.setBaseSize(QtCore.QSize(0, 20))
        self.data_selected_infos.setObjectName(_fromUtf8("data_selected_infos"))
        self.verticalLayout_9.addWidget(self.data_selected_infos)
        self.label_2 = QtGui.QLabel(self.data_infos_box)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_9.addWidget(self.label_2)
        self.data_general_infos = QtGui.QTextEdit(self.data_infos_box)
        self.data_general_infos.setMinimumSize(QtCore.QSize(0, 10))
        self.data_general_infos.setObjectName(_fromUtf8("data_general_infos"))
        self.verticalLayout_9.addWidget(self.data_general_infos)
        self.verticalLayout.addWidget(self.data_infos_box)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.data_preview_box = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview_box.sizePolicy().hasHeightForWidth())
        self.data_preview_box.setSizePolicy(sizePolicy)
        self.data_preview_box.setMinimumSize(QtCore.QSize(0, 20))
        self.data_preview_box.setSizeIncrement(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.data_preview_box.setFont(font)
        self.data_preview_box.setObjectName(_fromUtf8("data_preview_box"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.data_preview_box)
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.preview_widget = QtGui.QWidget(self.data_preview_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_widget.sizePolicy().hasHeightForWidth())
        self.preview_widget.setSizePolicy(sizePolicy)
        self.preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.preview_widget.setSizeIncrement(QtCore.QSize(0, 50))
        self.preview_widget.setBaseSize(QtCore.QSize(0, 300))
        self.preview_widget.setObjectName(_fromUtf8("preview_widget"))
        self.verticalLayout_10.addWidget(self.preview_widget)
        self.verticalLayout_2.addWidget(self.data_preview_box)
        self.data_instrument_box = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_instrument_box.sizePolicy().hasHeightForWidth())
        self.data_instrument_box.setSizePolicy(sizePolicy)
        self.data_instrument_box.setMinimumSize(QtCore.QSize(0, 80))
        self.data_instrument_box.setMaximumSize(QtCore.QSize(16777215, 80))
        self.data_instrument_box.setBaseSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_instrument_box.setFont(font)
        self.data_instrument_box.setObjectName(_fromUtf8("data_instrument_box"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.data_instrument_box)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.distance_source_detector_label = QtGui.QLabel(self.data_instrument_box)
        self.distance_source_detector_label.setMinimumSize(QtCore.QSize(80, 0))
        self.distance_source_detector_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.distance_source_detector_label.setObjectName(_fromUtf8("distance_source_detector_label"))
        self.horizontalLayout_11.addWidget(self.distance_source_detector_label)
        self.distance_source_detector = QtGui.QLineEdit(self.data_instrument_box)
        self.distance_source_detector.setObjectName(_fromUtf8("distance_source_detector"))
        self.horizontalLayout_11.addWidget(self.distance_source_detector)
        self.label_6 = QtGui.QLabel(self.data_instrument_box)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.line_3 = QtGui.QFrame(self.data_instrument_box)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_14.addWidget(self.line_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_3 = QtGui.QLabel(self.data_instrument_box)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.beam_rate = QtGui.QComboBox(self.data_instrument_box)
        self.beam_rate.setMinimumSize(QtCore.QSize(70, 0))
        self.beam_rate.setMaximumSize(QtCore.QSize(70, 16777215))
        self.beam_rate.setObjectName(_fromUtf8("beam_rate"))
        self.beam_rate.addItem(_fromUtf8(""))
        self.beam_rate.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.beam_rate)
        self.label_4 = QtGui.QLabel(self.data_instrument_box)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.line_2 = QtGui.QFrame(self.data_instrument_box)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_14.addWidget(self.line_2)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(self.data_instrument_box)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.detector_offset = QtGui.QLineEdit(self.data_instrument_box)
        self.detector_offset.setObjectName(_fromUtf8("detector_offset"))
        self.horizontalLayout_13.addWidget(self.detector_offset)
        self.micro_s = QtGui.QLabel(self.data_instrument_box)
        self.micro_s.setObjectName(_fromUtf8("micro_s"))
        self.horizontalLayout_13.addWidget(self.micro_s)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.line_4 = QtGui.QFrame(self.data_instrument_box)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_14.addWidget(self.line_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.delta_lambda_label = QtGui.QLabel(self.data_instrument_box)
        self.delta_lambda_label.setMinimumSize(QtCore.QSize(20, 0))
        self.delta_lambda_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.delta_lambda_label.setObjectName(_fromUtf8("delta_lambda_label"))
        self.horizontalLayout_12.addWidget(self.delta_lambda_label)
        self.delta_lambda_value = QtGui.QLabel(self.data_instrument_box)
        self.delta_lambda_value.setObjectName(_fromUtf8("delta_lambda_value"))
        self.horizontalLayout_12.addWidget(self.delta_lambda_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.data_instrument_box)
        self.horizontalLayout.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter_4 = QtGui.QSplitter(self.tab_3)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.import_normalized_data = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_normalized_data.sizePolicy().hasHeightForWidth())
        self.import_normalized_data.setSizePolicy(sizePolicy)
        self.import_normalized_data.setObjectName(_fromUtf8("import_normalized_data"))
        self.horizontalLayout_2.addWidget(self.import_normalized_data)
        self.normalized_folder = QtGui.QLabel(self.layoutWidget1)
        self.normalized_folder.setText(_fromUtf8(""))
        self.normalized_folder.setObjectName(_fromUtf8("normalized_folder"))
        self.horizontalLayout_2.addWidget(self.normalized_folder)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.list_normalized = QtGui.QListWidget(self.layoutWidget1)
        self.list_normalized.setObjectName(_fromUtf8("list_normalized"))
        self.verticalLayout_4.addWidget(self.list_normalized)
        self.groupBox_5 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(100, 200))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_11.addWidget(self.label_9)
        self.normalized_selected_infos = QtGui.QTextEdit(self.groupBox_5)
        self.normalized_selected_infos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_selected_infos.sizePolicy().hasHeightForWidth())
        self.normalized_selected_infos.setSizePolicy(sizePolicy)
        self.normalized_selected_infos.setMinimumSize(QtCore.QSize(0, 50))
        self.normalized_selected_infos.setObjectName(_fromUtf8("normalized_selected_infos"))
        self.verticalLayout_11.addWidget(self.normalized_selected_infos)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.normalized_general_infos = QtGui.QTextEdit(self.groupBox_5)
        self.normalized_general_infos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_general_infos.sizePolicy().hasHeightForWidth())
        self.normalized_general_infos.setSizePolicy(sizePolicy)
        self.normalized_general_infos.setMinimumSize(QtCore.QSize(0, 50))
        self.normalized_general_infos.setObjectName(_fromUtf8("normalized_general_infos"))
        self.verticalLayout_11.addWidget(self.normalized_general_infos)
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.normalized_preview_widget_2 = MPLWidget(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_preview_widget_2.sizePolicy().hasHeightForWidth())
        self.normalized_preview_widget_2.setSizePolicy(sizePolicy)
        self.normalized_preview_widget_2.setMinimumSize(QtCore.QSize(0, 300))
        self.normalized_preview_widget_2.setObjectName(_fromUtf8("normalized_preview_widget_2"))
        self.verticalLayout_13.addWidget(self.normalized_preview_widget_2)
        self.groupBox_6 = QtGui.QGroupBox(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.normalized_preview_widget = MPLWidget(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalized_preview_widget.sizePolicy().hasHeightForWidth())
        self.normalized_preview_widget.setSizePolicy(sizePolicy)
        self.normalized_preview_widget.setMinimumSize(QtCore.QSize(0, 300))
        self.normalized_preview_widget.setObjectName(_fromUtf8("normalized_preview_widget"))
        self.verticalLayout_12.addWidget(self.normalized_preview_widget)
        self.horizontalLayout_7.addWidget(self.splitter_4)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1534, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSteps = QtGui.QMenu(self.menubar)
        self.menuSteps.setObjectName(_fromUtf8("menuSteps"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Data = QtGui.QAction(MainWindow)
        self.action1_Data.setObjectName(_fromUtf8("action1_Data"))
        self.action2_Normalization = QtGui.QAction(MainWindow)
        self.action2_Normalization.setEnabled(True)
        self.action2_Normalization.setObjectName(_fromUtf8("action2_Normalization"))
        self.action3_Binning = QtGui.QAction(MainWindow)
        self.action3_Binning.setObjectName(_fromUtf8("action3_Binning"))
        self.action4_Fitting = QtGui.QAction(MainWindow)
        self.action4_Fitting.setObjectName(_fromUtf8("action4_Fitting"))
        self.action5_Results = QtGui.QAction(MainWindow)
        self.action5_Results.setObjectName(_fromUtf8("action5_Results"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action1_Raw_Data = QtGui.QAction(MainWindow)
        self.action1_Raw_Data.setObjectName(_fromUtf8("action1_Raw_Data"))
        self.action2_Normalization_2 = QtGui.QAction(MainWindow)
        self.action2_Normalization_2.setObjectName(_fromUtf8("action2_Normalization_2"))
        self.action3_Normalized_Data = QtGui.QAction(MainWindow)
        self.action3_Normalized_Data.setObjectName(_fromUtf8("action3_Normalized_Data"))
        self.menuSteps.addAction(self.action1_Raw_Data)
        self.menuSteps.addAction(self.action2_Normalization_2)
        self.menuSteps.addAction(self.action3_Normalized_Data)
        self.menuSteps.addAction(self.action3_Binning)
        self.menuSteps.addAction(self.action4_Fitting)
        self.menuSteps.addAction(self.action5_Results)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSteps.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.import_sample_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sample_import_button_clicked)
        QtCore.QObject.connect(self.import_time_spectra_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.time_spectra_import_button_clicked)
        QtCore.QObject.connect(self.import_open_beam_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.open_beam_import_button_clicked)
        QtCore.QObject.connect(self.list_sample, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.sample_list_selection_changed)
        QtCore.QObject.connect(self.list_open_beam, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.open_beam_list_selection_changed)
        QtCore.QObject.connect(self.list_sample, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainWindow.sample_list_right_click)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.load_data_tab_changed)
        QtCore.QObject.connect(self.preview_time_spectra_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.time_spectra_preview_button_clicked)
        QtCore.QObject.connect(self.import_normalized_data, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.normalized_import_button_clicked)
        QtCore.QObject.connect(self.list_normalized, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.normalized_list_selection_changed)
        QtCore.QObject.connect(self.distance_source_detector, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.update_delta_lambda)
        QtCore.QObject.connect(self.beam_rate, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.update_delta_lambda)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.import_sample_button.setText(_translate("MainWindow", "Import ...", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sample_toolbox), _translate("MainWindow", " Sample", None))
        self.import_open_beam_button.setText(_translate("MainWindow", "Import ...", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.open_beam_toolbox), _translate("MainWindow", " Open Beam", None))
        self.groupBox.setTitle(_translate("MainWindow", "Time Spectra", None))
        self.import_time_spectra_button.setText(_translate("MainWindow", "Import ...", None))
        self.preview_time_spectra_button.setText(_translate("MainWindow", "Preview ...", None))
        self.data_infos_box.setTitle(_translate("MainWindow", "infos", None))
        self.label.setText(_translate("MainWindow", "Selected File", None))
        self.label_2.setText(_translate("MainWindow", "All Files", None))
        self.data_preview_box.setTitle(_translate("MainWindow", "Sample Image Preview", None))
        self.data_instrument_box.setTitle(_translate("MainWindow", "instrument", None))
        self.distance_source_detector_label.setText(_translate("MainWindow", "d source-detector", None))
        self.distance_source_detector.setText(_translate("MainWindow", "15", None))
        self.label_6.setText(_translate("MainWindow", "m", None))
        self.label_3.setText(_translate("MainWindow", "Beam Rate", None))
        self.beam_rate.setItemText(0, _translate("MainWindow", "60", None))
        self.beam_rate.setItemText(1, _translate("MainWindow", "30", None))
        self.label_4.setText(_translate("MainWindow", "Hz", None))
        self.label_7.setText(_translate("MainWindow", "Detector offset", None))
        self.detector_offset.setText(_translate("MainWindow", "5000", None))
        self.micro_s.setText(_translate("MainWindow", "micros", None))
        self.delta_lambda_label.setText(_translate("MainWindow", "delta_lambda:", None))
        self.delta_lambda_value.setText(_translate("MainWindow", "N/A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1 - Load Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2 - Normalization", None))
        self.import_normalized_data.setText(_translate("MainWindow", "Import ...", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "infos", None))
        self.label_9.setText(_translate("MainWindow", "Selection", None))
        self.label_10.setText(_translate("MainWindow", "All Files", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Bragg Edges", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "preview", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3 - Normalized Data", None))
        self.menuSteps.setTitle(_translate("MainWindow", "Steps", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.action1_Data.setText(_translate("MainWindow", "1. Data", None))
        self.action2_Normalization.setText(_translate("MainWindow", "2. Normalization", None))
        self.action3_Binning.setText(_translate("MainWindow", "4. Binning", None))
        self.action4_Fitting.setText(_translate("MainWindow", "5. Fitting", None))
        self.action5_Results.setText(_translate("MainWindow", "6. Strain Mapping", None))
        self.actionAbout.setText(_translate("MainWindow", "About ...", None))
        self.action1_Raw_Data.setText(_translate("MainWindow", "1. Raw Data", None))
        self.action2_Normalization_2.setText(_translate("MainWindow", "2. Normalization", None))
        self.action3_Normalized_Data.setText(_translate("MainWindow", "3. Normalized Data", None))

from .mplwidget import MPLWidget
