# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_roiEditor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(446, 418)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_roi_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.add_roi_button.setFont(font)
        self.add_roi_button.setObjectName("add_roi_button")
        self.horizontalLayout.addWidget(self.add_roi_button)
        self.remove_roi_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_roi_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.remove_roi_button.setFont(font)
        self.remove_roi_button.setObjectName("remove_roi_button")
        self.horizontalLayout.addWidget(self.remove_roi_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Data = QtWidgets.QAction(MainWindow)
        self.action1_Data.setObjectName("action1_Data")
        self.action2_Normalization = QtWidgets.QAction(MainWindow)
        self.action2_Normalization.setEnabled(True)
        self.action2_Normalization.setObjectName("action2_Normalization")
        self.action3_Binning = QtWidgets.QAction(MainWindow)
        self.action3_Binning.setObjectName("action3_Binning")
        self.action4_Fitting = QtWidgets.QAction(MainWindow)
        self.action4_Fitting.setObjectName("action4_Fitting")
        self.action5_Results = QtWidgets.QAction(MainWindow)
        self.action5_Results.setObjectName("action5_Results")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action1_Raw_Data = QtWidgets.QAction(MainWindow)
        self.action1_Raw_Data.setObjectName("action1_Raw_Data")
        self.action2_Normalization_2 = QtWidgets.QAction(MainWindow)
        self.action2_Normalization_2.setObjectName("action2_Normalization_2")
        self.action3_Normalized_Data = QtWidgets.QAction(MainWindow)
        self.action3_Normalized_Data.setObjectName("action3_Normalized_Data")

        self.retranslateUi(MainWindow)
        self.add_roi_button.clicked.connect(MainWindow.add_roi_button_clicked)
        self.remove_roi_button.clicked.connect(MainWindow.remove_roi_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X0"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y0"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Width"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Height"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Groups"))
        self.add_roi_button.setText(_translate("MainWindow", "+"))
        self.remove_roi_button.setText(_translate("MainWindow", "-"))
        self.action1_Data.setText(_translate("MainWindow", "1. Data"))
        self.action2_Normalization.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Binning.setText(_translate("MainWindow", "4. Binning"))
        self.action4_Fitting.setText(_translate("MainWindow", "5. Fitting"))
        self.action5_Results.setText(_translate("MainWindow", "6. Strain Mapping"))
        self.actionAbout.setText(_translate("MainWindow", "About ..."))
        self.action1_Raw_Data.setText(_translate("MainWindow", "1. Raw Data"))
        self.action2_Normalization_2.setText(_translate("MainWindow", "2. Normalization"))
        self.action3_Normalized_Data.setText(_translate("MainWindow", "3. Normalized Data"))

