# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_strainMapping.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(310, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName("groupBox")
        self.d0_units_label = QtWidgets.QLabel(self.groupBox)
        self.d0_units_label.setGeometry(QtCore.QRect(282, 31, 63, 16))
        self.d0_units_label.setObjectName("d0_units_label")
        self.d0_label = QtWidgets.QLabel(self.groupBox)
        self.d0_label.setGeometry(QtCore.QRect(15, 31, 16, 16))
        self.d0_label.setObjectName("d0_label")
        self.d0_label_2 = QtWidgets.QLabel(self.groupBox)
        self.d0_label_2.setGeometry(QtCore.QRect(148, 31, 16, 16))
        self.d0_label_2.setObjectName("d0_label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(172, 31, 100, 21))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(38, 31, 100, 21))
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recap_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.recap_tabs.setObjectName("recap_tabs")
        self.strain_mapping_tab = QtWidgets.QWidget()
        self.strain_mapping_tab.setObjectName("strain_mapping_tab")
        self.recap_tabs.addTab(self.strain_mapping_tab, "")
        self.sigma_tab = QtWidgets.QWidget()
        self.sigma_tab.setObjectName("sigma_tab")
        self.recap_tabs.addTab(self.sigma_tab, "")
        self.alpha_tab = QtWidgets.QWidget()
        self.alpha_tab.setObjectName("alpha_tab")
        self.recap_tabs.addTab(self.alpha_tab, "")
        self.horizontalLayout_3.addWidget(self.recap_tabs)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(80, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.strain_mapping_colorbar_window = QtWidgets.QWidget()
        self.strain_mapping_colorbar_window.setObjectName("strain_mapping_colorbar_window")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.strain_mapping_colorbar_window)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.strain_mapping_colorbar = QtWidgets.QTableWidget(self.strain_mapping_colorbar_window)
        self.strain_mapping_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.strain_mapping_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.strain_mapping_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strain_mapping_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strain_mapping_colorbar.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.strain_mapping_colorbar.setObjectName("strain_mapping_colorbar")
        self.strain_mapping_colorbar.setColumnCount(1)
        self.strain_mapping_colorbar.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.strain_mapping_colorbar.setHorizontalHeaderItem(0, item)
        self.strain_mapping_colorbar.horizontalHeader().setVisible(False)
        self.strain_mapping_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.strain_mapping_colorbar)
        self.stackedWidget.addWidget(self.strain_mapping_colorbar_window)
        self.sigma_colorbar_window = QtWidgets.QWidget()
        self.sigma_colorbar_window.setObjectName("sigma_colorbar_window")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.sigma_colorbar_window)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sigma_colorbar = QtWidgets.QTableWidget(self.sigma_colorbar_window)
        self.sigma_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.sigma_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.sigma_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sigma_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sigma_colorbar.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.sigma_colorbar.setObjectName("sigma_colorbar")
        self.sigma_colorbar.setColumnCount(1)
        self.sigma_colorbar.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.sigma_colorbar.setHorizontalHeaderItem(0, item)
        self.sigma_colorbar.horizontalHeader().setVisible(False)
        self.sigma_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.sigma_colorbar)
        self.stackedWidget.addWidget(self.sigma_colorbar_window)
        self.alpha_colorbar_window = QtWidgets.QWidget()
        self.alpha_colorbar_window.setObjectName("alpha_colorbar_window")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.alpha_colorbar_window)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.alpha_colorbar = QtWidgets.QTableWidget(self.alpha_colorbar_window)
        self.alpha_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.alpha_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.alpha_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha_colorbar.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.alpha_colorbar.setObjectName("alpha_colorbar")
        self.alpha_colorbar.setColumnCount(1)
        self.alpha_colorbar.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.alpha_colorbar.setHorizontalHeaderItem(0, item)
        self.alpha_colorbar.horizontalHeader().setVisible(False)
        self.alpha_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.alpha_colorbar)
        self.stackedWidget.addWidget(self.alpha_colorbar_window)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.transparency_slider = QtWidgets.QSlider(self.centralwidget)
        self.transparency_slider.setProperty("value", 50)
        self.transparency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.transparency_slider.setObjectName("transparency_slider")
        self.horizontalLayout_2.addWidget(self.transparency_slider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.recap_tabs.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.recap_tabs.currentChanged['int'].connect(MainWindow.tab_index_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strain Mapping"))
        self.groupBox.setTitle(_translate("MainWindow", "Unstrained d-spacing"))
        self.d0_units_label.setText(_translate("MainWindow", "Angstroms"))
        self.d0_label.setText(_translate("MainWindow", "d0"))
        self.d0_label_2.setText(_translate("MainWindow", "+/-"))
        self.pushButton.setText(_translate("MainWindow", "Export Image ..."))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.strain_mapping_tab), _translate("MainWindow", "Strain Mapping"))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.sigma_tab), _translate("MainWindow", "Sigma"))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.alpha_tab), _translate("MainWindow", "Alpha"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.strain_mapping_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.sigma_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.sigma_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.alpha_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.alpha_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label.setText(_translate("MainWindow", "Transparency"))

