name: ibeatles
channels:
  - conda-forge
dependencies:
  - python
  - python-dateutil
  - pip
  - cycler
  - freetype
  - libpng
  - matplotlib
  - mkl
  - numpy
  - openssl
  - pyparsing
  - pyqt
  - pytz
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - wheel
  - zlib
  - pyqtgraph=0.12.1
  - lmfit
  - qtpy
  - versioneer
  - astropy
  - pip:
      - neutronbraggedge
      - changepy
      - NeuNorm
