name: ibeatles
channels:
  - neutronimaging
  - conda-forge
dependencies:
  # base
  - python>=3.10
  - pip
  - versioningit
  - ipython
  - pydantic
  # packaging
  - boa
  - conda-build
  - conda-verify
  - python-build
  # test
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-repeat  # for debugging unstable tests
  # compute
  - astropy
  - lmfit
  - neunorm
  # storage
  - h5py
  - sqlite
  - zlib
  # Qt
  - qt=5.15.8 # Avoid unexpected qt upgrades
  - qtpy>=1.9.0
  - pyqt>=5.15,<6
  - pyqtgraph
  # visualization
  - matplotlib
  # utilities
  - pre-commit
  - pyparsing  # grammar
  - pytz  # time zone
  - readline  # reading command line
  # pip
  - pip:
      - neutronbraggedge  # brag edge analysis
      - changepy  # change point detection
