name: ibeatles
channels:
  - conda-forge
dependencies:
  - cycler
  - freetype
  - libpng
  - matplotlib
  - mkl
  - numpy
  - openssl
  - pip
  - pyparsing
  - pyqt=5.9.2
  - python=3.7
  - python-dateutil
  - pytz
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - wheel
  - zlib
  - pyqtgraph=0.12.1
  - lmfit
  - qtpy
  - versioneer
  - astropy
  - neutronbraggedge
