name: ibeatles
channels:
  - conda-forge
dependencies:
  - python
  - python-dateutil
  - pip
  - cycler
  - freetype
  - libpng
  - matplotlib
#  - mkl
  - numpy
  - openssl
  - pyparsing
  - pyqt
  - pytz
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - wheel
  - zlib
  - pyqtgraph
  - qtpy
  - versioneer
  - astropy
  - ipython
  - pip:
      - neutronbraggedge
      - changepy
      - NeuNorm
      - lmfit
      - pytest
