# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_fittingSetVariables.ui'
#
# Created: Wed Mar 22 11:10:18 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1222, 772)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.d_spacing_button = QtGui.QRadioButton(self.groupBox)
        self.d_spacing_button.setChecked(True)
        self.d_spacing_button.setObjectName(_fromUtf8("d_spacing_button"))
        self.horizontalLayout.addWidget(self.d_spacing_button)
        self.sigma_button = QtGui.QRadioButton(self.groupBox)
        self.sigma_button.setObjectName(_fromUtf8("sigma_button"))
        self.horizontalLayout.addWidget(self.sigma_button)
        self.alpha_button = QtGui.QRadioButton(self.groupBox)
        self.alpha_button.setObjectName(_fromUtf8("alpha_button"))
        self.horizontalLayout.addWidget(self.alpha_button)
        self.a1_button = QtGui.QRadioButton(self.groupBox)
        self.a1_button.setObjectName(_fromUtf8("a1_button"))
        self.horizontalLayout.addWidget(self.a1_button)
        self.a2_button = QtGui.QRadioButton(self.groupBox)
        self.a2_button.setObjectName(_fromUtf8("a2_button"))
        self.horizontalLayout.addWidget(self.a2_button)
        self.a5_button = QtGui.QRadioButton(self.groupBox)
        self.a5_button.setObjectName(_fromUtf8("a5_button"))
        self.horizontalLayout.addWidget(self.a5_button)
        self.a6_button = QtGui.QRadioButton(self.groupBox)
        self.a6_button.setObjectName(_fromUtf8("a6_button"))
        self.horizontalLayout.addWidget(self.a6_button)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.variable_table = QtGui.QTableWidget(self.centralwidget)
        self.variable_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.variable_table.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.variable_table.setObjectName(_fromUtf8("variable_table"))
        self.variable_table.setColumnCount(0)
        self.variable_table.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.variable_table)
        self.colorscale_table = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorscale_table.sizePolicy().hasHeightForWidth())
        self.colorscale_table.setSizePolicy(sizePolicy)
        self.colorscale_table.setMinimumSize(QtCore.QSize(75, 0))
        self.colorscale_table.setMaximumSize(QtCore.QSize(75, 16777215))
        self.colorscale_table.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.colorscale_table.setObjectName(_fromUtf8("colorscale_table"))
        self.colorscale_table.setColumnCount(1)
        self.colorscale_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.colorscale_table.setHorizontalHeaderItem(0, item)
        self.colorscale_table.horizontalHeader().setVisible(False)
        self.colorscale_table.horizontalHeader().setStretchLastSection(True)
        self.colorscale_table.verticalHeader().setVisible(False)
        self.colorscale_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.colorscale_table)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.active_label = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 35, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 28, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 146, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 35, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 28, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 146, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 142, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 204, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.active_label.setPalette(palette)
        self.active_label.setObjectName(_fromUtf8("active_label"))
        self.horizontalLayout_5.addWidget(self.active_label)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.locked_label = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(193, 22, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 22, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.locked_label.setPalette(palette)
        self.locked_label.setObjectName(_fromUtf8("locked_label"))
        self.horizontalLayout_5.addWidget(self.locked_label)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fixed_label = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.fixed_label.setPalette(palette)
        self.fixed_label.setObjectName(_fromUtf8("fixed_label"))
        self.horizontalLayout_5.addWidget(self.fixed_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.advanced_selection_cell_size_slider = QtGui.QSlider(self.centralwidget)
        self.advanced_selection_cell_size_slider.setMinimum(10)
        self.advanced_selection_cell_size_slider.setMaximum(80)
        self.advanced_selection_cell_size_slider.setProperty("value", 20)
        self.advanced_selection_cell_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.advanced_selection_cell_size_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.advanced_selection_cell_size_slider.setObjectName(_fromUtf8("advanced_selection_cell_size_slider"))
        self.horizontalLayout_5.addWidget(self.advanced_selection_cell_size_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.new_value_text_edit = QtGui.QLineEdit(self.centralwidget)
        self.new_value_text_edit.setMinimumSize(QtCore.QSize(100, 0))
        self.new_value_text_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.new_value_text_edit.setObjectName(_fromUtf8("new_value_text_edit"))
        self.horizontalLayout_2.addWidget(self.new_value_text_edit)
        self.apply_button = QtGui.QPushButton(self.centralwidget)
        self.apply_button.setMinimumSize(QtCore.QSize(250, 0))
        self.apply_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.horizontalLayout_2.addWidget(self.apply_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.advanced_selection_cell_size_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.selection_cell_size_changed)
        QtCore.QObject.connect(self.d_spacing_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.sigma_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.alpha_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.a1_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.a2_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.a5_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.a6_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update_table)
        QtCore.QObject.connect(self.variable_table, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainWindow.variable_table_right_click)
        QtCore.QObject.connect(self.apply_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.apply_new_value_to_selection)
        QtCore.QObject.connect(self.new_value_text_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.apply_new_value_to_selection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Variables", None))
        self.d_spacing_button.setText(_translate("MainWindow", "D-spacing", None))
        self.sigma_button.setText(_translate("MainWindow", "Sigma", None))
        self.alpha_button.setText(_translate("MainWindow", "Alpha", None))
        self.a1_button.setText(_translate("MainWindow", "A1", None))
        self.a2_button.setText(_translate("MainWindow", "A2", None))
        self.a5_button.setText(_translate("MainWindow", "A5", None))
        self.a6_button.setText(_translate("MainWindow", "A6", None))
        item = self.colorscale_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        self.active_label.setText(_translate("MainWindow", "Active Bin", None))
        self.label_4.setText(_translate("MainWindow", " ", None))
        self.locked_label.setText(_translate("MainWindow", "Bin Locked", None))
        self.label_6.setText(_translate("MainWindow", " ", None))
        self.fixed_label.setText(_translate("MainWindow", "Fixed", None))
        self.label_2.setText(_translate("MainWindow", "Cells Size", None))
        self.label.setText(_translate("MainWindow", "New Value", None))
        self.apply_button.setText(_translate("MainWindow", "Apply New Value to Selection", None))

import icons_rc
