# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_strainMapping.ui'
#
# Created: Tue Jan  8 07:47:40 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1140, 743)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(310, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.d0_units_label = QtGui.QLabel(self.groupBox)
        self.d0_units_label.setGeometry(QtCore.QRect(282, 31, 63, 16))
        self.d0_units_label.setObjectName(_fromUtf8("d0_units_label"))
        self.d0_label = QtGui.QLabel(self.groupBox)
        self.d0_label.setGeometry(QtCore.QRect(15, 31, 16, 16))
        self.d0_label.setObjectName(_fromUtf8("d0_label"))
        self.d0_label_2 = QtGui.QLabel(self.groupBox)
        self.d0_label_2.setGeometry(QtCore.QRect(148, 31, 16, 16))
        self.d0_label_2.setObjectName(_fromUtf8("d0_label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(172, 31, 100, 21))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(38, 31, 100, 21))
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.recap_tabs = QtGui.QTabWidget(self.centralwidget)
        self.recap_tabs.setObjectName(_fromUtf8("recap_tabs"))
        self.strain_mapping_tab = QtGui.QWidget()
        self.strain_mapping_tab.setObjectName(_fromUtf8("strain_mapping_tab"))
        self.recap_tabs.addTab(self.strain_mapping_tab, _fromUtf8(""))
        self.sigma_tab = QtGui.QWidget()
        self.sigma_tab.setObjectName(_fromUtf8("sigma_tab"))
        self.recap_tabs.addTab(self.sigma_tab, _fromUtf8(""))
        self.alpha_tab = QtGui.QWidget()
        self.alpha_tab.setObjectName(_fromUtf8("alpha_tab"))
        self.recap_tabs.addTab(self.alpha_tab, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.recap_tabs)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(80, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.strain_mapping_colorbar_window = QtGui.QWidget()
        self.strain_mapping_colorbar_window.setObjectName(_fromUtf8("strain_mapping_colorbar_window"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.strain_mapping_colorbar_window)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.strain_mapping_colorbar = QtGui.QTableWidget(self.strain_mapping_colorbar_window)
        self.strain_mapping_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.strain_mapping_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.strain_mapping_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strain_mapping_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strain_mapping_colorbar.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.strain_mapping_colorbar.setObjectName(_fromUtf8("strain_mapping_colorbar"))
        self.strain_mapping_colorbar.setColumnCount(1)
        self.strain_mapping_colorbar.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.strain_mapping_colorbar.setHorizontalHeaderItem(0, item)
        self.strain_mapping_colorbar.horizontalHeader().setVisible(False)
        self.strain_mapping_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.strain_mapping_colorbar)
        self.stackedWidget.addWidget(self.strain_mapping_colorbar_window)
        self.sigma_colorbar_window = QtGui.QWidget()
        self.sigma_colorbar_window.setObjectName(_fromUtf8("sigma_colorbar_window"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.sigma_colorbar_window)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sigma_colorbar = QtGui.QTableWidget(self.sigma_colorbar_window)
        self.sigma_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.sigma_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.sigma_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sigma_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sigma_colorbar.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.sigma_colorbar.setObjectName(_fromUtf8("sigma_colorbar"))
        self.sigma_colorbar.setColumnCount(1)
        self.sigma_colorbar.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.sigma_colorbar.setHorizontalHeaderItem(0, item)
        self.sigma_colorbar.horizontalHeader().setVisible(False)
        self.sigma_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.sigma_colorbar)
        self.stackedWidget.addWidget(self.sigma_colorbar_window)
        self.alpha_colorbar_window = QtGui.QWidget()
        self.alpha_colorbar_window.setObjectName(_fromUtf8("alpha_colorbar_window"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.alpha_colorbar_window)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.alpha_colorbar = QtGui.QTableWidget(self.alpha_colorbar_window)
        self.alpha_colorbar.setMinimumSize(QtCore.QSize(50, 200))
        self.alpha_colorbar.setMaximumSize(QtCore.QSize(50, 450))
        self.alpha_colorbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha_colorbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha_colorbar.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.alpha_colorbar.setObjectName(_fromUtf8("alpha_colorbar"))
        self.alpha_colorbar.setColumnCount(1)
        self.alpha_colorbar.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.alpha_colorbar.setHorizontalHeaderItem(0, item)
        self.alpha_colorbar.horizontalHeader().setVisible(False)
        self.alpha_colorbar.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.alpha_colorbar)
        self.stackedWidget.addWidget(self.alpha_colorbar_window)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.transparency_slider = QtGui.QSlider(self.centralwidget)
        self.transparency_slider.setProperty("value", 50)
        self.transparency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.transparency_slider.setObjectName(_fromUtf8("transparency_slider"))
        self.horizontalLayout_2.addWidget(self.transparency_slider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.recap_tabs.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.recap_tabs, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.tab_index_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Strain Mapping", None))
        self.groupBox.setTitle(_translate("MainWindow", "Unstrained d-spacing", None))
        self.d0_units_label.setText(_translate("MainWindow", "Angstroms", None))
        self.d0_label.setText(_translate("MainWindow", "d0", None))
        self.d0_label_2.setText(_translate("MainWindow", "+/-", None))
        self.pushButton.setText(_translate("MainWindow", "Export Image ...", None))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.strain_mapping_tab), _translate("MainWindow", "Strain Mapping", None))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.sigma_tab), _translate("MainWindow", "Sigma", None))
        self.recap_tabs.setTabText(self.recap_tabs.indexOf(self.alpha_tab), _translate("MainWindow", "Alpha", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.strain_mapping_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.sigma_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.sigma_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.alpha_colorbar.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.alpha_colorbar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        self.label.setText(_translate("MainWindow", "Transparency", None))

