#!/usr/bin/env python

import sys
import os
import time

import PyQt4
import PyQt4.QtCore as QtCore
import PyQt4.QtGui as QtGui

import ibeatles.interfaces.ui_mainWindow

from ibeatles.step1.data_handler import DataHandler
from ibeatles.step1.gui_handler import Step1GuiHandler
from ibeatles.step1.time_spectra_handler import TimeSpectraHandler

from ibeatles.step3.gui_handler import Step3GuiHandler

from ibeatles.utilities.retrieve_data_infos import RetrieveSelectedFileDataInfos, RetrieveGeneralFileInfos
from ibeatles.utilities.list_data_handler import ListDataHandler


class MainWindow(PyQt4.QtGui.QMainWindow, ibeatles.interfaces.ui_mainWindow.Ui_MainWindow):
    """ Main FastGR window
    """

    DEBUGGING = True

    def __init__(self):
        """ Initialization
        Parameters
        ----------
        """
        # Base class
        QtGui.QMainWindow.__init__(self)

        # Initialize the UI widgets
        self.ui = ibeatles.interfaces.ui_mainWindow.Ui_MainWindow()
        self.ui.setupUi(self)

        self.setup()
        self.init_interface()
        
    def init_interface(self):
        o_gui = Step1GuiHandler(parent=self)
        o_gui.init_gui()
        
    def setup(self):
        if self.DEBUGGING:
            current_folder = '/Volumes/My Book Thunderbolt Duo/iBeatles/test_data/'
        else:
            current_folder = os.getcwd()

        self.sample_folder = current_folder
        self.ob_folder = current_folder
        self.normalized_folder = current_folder
        self.time_spectra_folder = current_folder
    
        self.data_metadata = {'sample': {'title': "Select folder or list of files",
                                         'folder': current_folder,
                                         'general_infos': None},
                              'ob': {'title': 'Select folder or list of files',
                                     'folder': current_folder,
                                     'general_infos': None},
                              'normalized': {'title': 'Select folder or list of files',
                                             'folder': current_folder,
                                             'general_infos': None},
                              'time_spectra': {'title': 'Select file',
                                               'folder': current_folder,
                                               'general_infos': None}}
        
        self.data_files = {'sample': [],
                           'ob': [],
                           'normalized': [],
                           'time_spectra': []}

    #TAB 1, 2 and 3
    
    def retrieve_general_infos(self, data_type = 'sample'):
        o_general_infos = RetrieveGeneralFileInfos(parent = self, data_type = data_type)
        o_general_infos.update()
    
    def retrieve_selected_row_infos(self, data_type = 'sample'):
        if data_type == 'sample':
            self.sample_retrieve_selected_row_infos()
        elif data_type == 'ob':
            self.open_beam_retrieve_selected_row_infos()
        elif data_type == 'normalized':
            self.normalized_retrieve_selected_row_infos()

    #TAB 1: Load Data Tab
    
    def sample_import_button_clicked(self):
        self.loading_flag = True
        o_load = DataHandler(parent = self)
        o_load.retrieve_files(data_type = 'sample')
        if not o_load.user_canceled:
            self.select_load_data_row(data_type = 'sample', row = 0)
            self.retrieve_general_infos(data_type = 'sample')
            self.retrieve_selected_row_infos(data_type = 'sample')

    def select_load_data_row(self, data_type='sample', row=0):
        o_gui = Step1GuiHandler(parent=self)
        o_gui.select_load_data_row(data_type=data_type,
                                   row=row)
                                                           
    def sample_retrieve_selected_row_infos(self):
        o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'sample')
        o_retrieve_data_infos.update()

    def open_beam_retrieve_selected_row_infos(self):
        o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'ob')
        o_retrieve_data_infos.update()

    def sample_list_selection_changed(self):
        if not self.loading_flag:
            o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'sample')
            o_retrieve_data_infos.update()   
        else:
            self.loading_flag = False

    def sample_list_right_click(self, position):
        o_list_handler = ListDataHandler(parent = self)
        o_list_handler.right_click(position = position)

    def open_beam_import_button_clicked(self):
        o_load = DataHandler(parent = self)
        o_load.retrieve_files(data_type = 'ob')
        if not o_load.user_canceled:
            self.select_load_data_row(data_type = 'ob', row = 0)
            self.retrieve_general_infos(data_type = 'ob')
            self.retrieve_selected_row_infos(data_type = 'ob')

    def open_beam_list_selection_changed(self):
        o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'ob')
        o_retrieve_data_infos.update()

    def time_spectra_import_button_clicked(self):
        o_load = DataHandler(parent = self)
        o_load.retrieve_time_spectra(auto_load = False)

    def time_spectra_preview_button_clicked(self):
        o_time_spectra = TimeSpectraHandler(parent = self)
        o_time_spectra.display()
                
    def load_data_tab_changed(self, tab_index):
        o_gui = Step1GuiHandler(parent = self)
        o_gui.load_data_tab_changed(tab_index = tab_index)
    
    #TAB 3: Normalized Data Tab
    
    def normalized_import_button_clicked(self):
        self.loading_flag = True
        o_load = DataHandler(parent = self)
        o_load.retrieve_files(data_type = 'normalized')
        if not o_load.user_canceled:
            self.select_normalized_row(row = 0)
            self.retrieve_general_infos(data_type = 'normalized')
            self.retrieve_selected_row_infos(data_type = 'normalized')
    
    def normalized_retrieve_selected_row_infos(self):
        o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'normalized')
        o_retrieve_data_infos.update()

    def select_normalized_row(self, row=0):
        o_gui = Step3GuiHandler(parent=self)
        o_gui.select_normalized_row(row=row)

    def normalized_list_selection_changed(self):
        if not self.loading_flag:
            o_retrieve_data_infos = RetrieveSelectedFileDataInfos(parent = self, data_type = 'normalized')
            o_retrieve_data_infos.update()   
        else:
            self.loading_flag = False


def main():
    app = PyQt4.QtGui.QApplication(sys.argv)
    #app.setWindowIcon(PyQt4.QtGui.QIcon(":/icon.png"))
    application = MainWindow()
    application.show()
    app.exec_()

if __name__ == '__main__':
    main()
