{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set url = project.get('urls', {}).get('homepage', 'https://github.com/ornlneutronimaging/iBeatles') %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
{% set build_number = 0 %}

package:
  name: ibeatles
  version: {{ version_number }}

source:
  path: ..

build:
  noarch: python
  number: {{ build_number }}
  string: py{{ python }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    - {{ PYTHON }} -m pip install git+https://github.com/ornlneutronimaging/BraggEdge.git --no-deps --no-build-isolation -vvv
    - {{ PYTHON }} -m pip install git+https://github.com/ruipgil/changepy.git --no-deps --no-build-isolation -vvv
    - {{ PYTHON }} -m pip install git+https://github.com/ornlneutronimaging/NeuNorm.git --no-deps --no-build-isolation -vvv

requirements:

  host:
    - python
    - pip
    - versioningit

  build:
    - pip
    - setuptools
    - versioningit

  run:
    - python {{ python }}
    - pip
    - setuptools
    - numpy
    - pandas <3
    - matplotlib
    - qt=5
    - qtpy
    - pyqt
    - loguru
    - h5py
    - args
    - pillow
    - astropy
    - pyqtgraph
    - scipy
    - lmfit
    - tqdm
    - tomli
    - pydantic
    - ipython
    # - neutronimaging::neunorm  # switch to pip install until we sorted out NeuNorm conda package version issue

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - JeanBilheux
    - kedokudo
