{% set data = load_setup_py_data() %}

package:
  name: "ibeatles"
  version: "10.31.23

source:
  path: ..

build:
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - matplotlib
    - qt=5
    - qtpy
    - pyqt
    - h5py
    - args
    - Pillow
    - versioneer
    - astropy
    - pyqtgraph
    - scipy
    - lmfit

test:
  imports:
    - ibeatles

about:
  home: https://github.com/neutronimaging/iBeatles
  license: GPL (version 3)
  license_family: GPL3
  license_file:
  summary: Bragg edge analysis

extra:
  recipe-maintainers:
    - JeanBilheux
