name: iBeatles tests
on: push
jobs:
    test-python-3-10:
        name: Check iBeatles tests using python 3.10 on ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: "3.10"

            - uses: mamba-org/setup-micromamba@v1
              with:
                micromamba-version: "1.3.1-0"
                environment-file: environment.yml
                init-shell: >-
                    bash
                    powershell
                cache-environment: true
                post-cleanup: 'all'

            - name: Install package
              run: python -m pip install -e . pytest
              shell: micromamba-shell {0}

            - name: Test package
              run: python -m pytest
              shell: micromamba-shell {0}
